### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by IvanAbadzhiev** [datproject/dat#1008]
Hello Guys, 
You have an Amazing project, really like it, but I have an issue when I try to download some file from another computer outside my network I receive this response
```
Dat could not find any connections for that link.
There may not be any sources online.
Run 'dat doctor' if you keep having trouble. 
```
And when I run a **dat doctor** command I receive
```
[info] Testing connection to public peer
[error] FAIL - Connection timeout, fail.
[error] FAIL - Connection timeout, fail.
[error] FAIL - Unable to connect to public server.
[error] FAIL - Data was not echoed back from public server.
[error] FAIL - Unable to connect to public server.
[error] FAIL - Data was not echoed back from public server.

[info] End of phase one (Public Server), moving on to phase two (Peer to Peer via DNS)

[error] Could not detect public ip / port
```

Environment information:
Windows 10
NodeJs - v8.11.2
Dat - 13.10.0

**Comment by pfrazee** [comment]
What kind of a network are you on? Is it possible there's a very restrictive firewall?

**Comment by AcidLeroy** [comment]
I'm having similar problems, mostly behind a university firewall. Does anyone have any suggestions to possibly get around this? I'm not opposed to hosting something centralized in the cloud to provide some kind of tunneling out of the university's network.

**Comment by Sigafoos** [comment]
I'm having this problem as well. On a corporate network so I suspect they have certain things locked down. Not sure if there's something I can do.

```❯ dat doctor                                                                                                                                                                                               
Welcome to Dat Doctor!

Software Info:
  darwin x64
  Node v11.8.0
  Dat Doctor v2.1.2
  dat v13.11.5

Running Basic Tests (Checks your Dat installation and network setup)

✖ Who am I?
    ERROR: Could not detect public ip / port
✔ Loaded native modules
✔ Resolved Dat Doctor Server
✔ Successful data transfer with Dat Doctor via TCP
✖ Public Peer Test via UDP Failed
  Unable to connect to Dat public server

FAIL
3 of 5 tests passed

Your network may be preventing you from using Dat.
For further troubleshooting, visit https://docs.datproject.org/troubleshooting

❯ dat doctor 778f8d955175c92e4ced5e4f5563f69bfec0c86cc6f670352c457943666fe639
Welcome to Dat Doctor!

Software Info:
  darwin x64
  Node v11.8.0
  Dat Doctor v2.1.2
  dat v13.11.5


✖ Who am I?
    ERROR: Could not detect public ip / port
✔ Loaded native modules


Joining existing Peer-to-Peer test:

  dat doctor 778f8d955175c92e4ced5e4f5563f69bfec0c86cc6f670352c457943666fe639

Trying to Connect:
  38.97.88.240:51192
```
It hangs there.

**Comment by okdistribute** [comment]
Try dat@next, I wonder if it works for you @Sigafoos, @IvanAbadzhiev ?

**Comment by VincentHanrion** [comment]
same problem : 

Welcome to Dat Doctor!

Software Info:
  darwin x64
  Node v14.0.0
  Dat Doctor v2.1.2
  dat v13.13.1

Running Basic Tests (Checks your Dat installation and network setup)

✖ Who am I?
    ERROR: Could not detect public ip / port
✔ Loaded native modules
✔ Resolved Dat Doctor Server
✔ Successful data transfer with Dat Doctor via TCP
✔ Successful data transfer with Dat Doctor via UDP

FAIL
4 of 5 tests passed

Your network may be preventing you from using Dat.
For further troubleshooting, visit https://docs.datproject.org/troubleshooting

**Comment by okdistribute** [comment]
@VincentHanrion can you try npm install -g dat@next?
