### ISSUE TITLE
Fix issue template - remove TODOs

### ISSUE THREAD

**Issue by joehand** [datproject/dat#1011]
Please remove TODOs from issue tempalte

I am reporting:

- [ ] a bug or unexpected behavior
- [x] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system:
* Node Version:
* Dat Version:

### Expected behavior

Not showing 1/4 things TODO in all the issues

**Comment by orbistertius** [comment]
[GitHub taks lists](https://help.github.com/articles/about-task-lists/) use the MarkDown checkbox syntax, so Dat issues have "1/4" because we usually report one of the four things: bug, general feedback, feature request, security issue.
