### ISSUE TITLE
v13.11.0: install script not working: missing binary distribution archives

### ISSUE THREAD

**Issue by orbistertius** [datproject/dat#1016]
I am reporting:

- [x] a bug or unexpected behavior
- [ ] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: Linux
* Node Version: 10.5.0
* Dat Version: 13.11.0

### Expected behavior

dat installed without using npm.

### Actual behavior

curl returns a "404 Not Found" for the binary distribution archive.
macOS and Windows distribution archives missing too.

### Debug Logs

    $ wget -qO- https://raw.githubusercontent.com/datproject/dat/master/download.sh | bash
    Fetching latest Dat release version from GitHub
    Downloading https://github.com/datproject/dat/releases/download/v13.11.0/dat-13.11.0-linux-x64.zip
    
    curl: (22) The requested URL returned error: 404 Not Found
    ============
    Error: download failed

**Comment by joehand** [comment]
Ah, thanks! 

Looks like the builds didn't get posted because tests are having issues right now. Will see if I can do it manually.

**Comment by joehand** [comment]
Thanks for reporting, should be fixed with the latest release: https://github.com/datproject/dat/releases/tag/v13.11.2. 

Let us know if you have more issues installing.
