### ISSUE TITLE
Possible perf_hooks memory leak detected.

### ISSUE THREAD

**Issue by berithpy** [datproject/dat#1022]
I am reporting:

- [x] a bug or unexpected behavior
- [ ] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: Ubuntu 18.04
* Node Version: 9.11.1
* Dat Version: 13.11.3
* Shell: fish

### Expected behavior

Share a folder and watch upload and download

### Actual behavior

Sharing a folder with ```dat share folder``` for more than 3 minutes prints ```(node:5968) Warning: Possible perf_hooks memory leak detected. There are 4307 entries in the Performance Timeline. Use the clear methods to remove entries that are no longer needed or set performance.maxEntries equal to a higher value (currently the maxEntries is 150).``` in the console. The number keeps increasing, 4307 was after 28 minutes of sharing a folder

### Debug Logs

  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.11.3 +7ms
  dat node v9.11.1 +0ms
  dat Sharing archive { _: [ 'memes/' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  watch: true,
  logspeed: 400,
  dir: 'memes/' } +0ms
  dat-node archive ready. version: 2 +0ms
  dat-node importFiles() { watch: true,
  dereference: true,
  count: true,
  indexing: true,
  _: [ 'memes/' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  logspeed: 400,
  dir: 'memes/',
  ignore: [Function: ignore] } +0ms
  dat-node IMPORT ignore: / +51ms
  dat-node IMPORT ignore: /.dat +1ms
  dat-node IMPORT ignore: /.dat/content.bitfield +5ms
  dat-node IMPORT ignore: /.dat/content.key +0ms
  dat-node IMPORT ignore: /.dat/content.secret_key +1ms
  dat-node IMPORT ignore: /.dat/content.signatures +0ms
  dat-node IMPORT ignore: /.dat/content.tree +1ms
  dat-node IMPORT ignore: /.dat/metadata.bitfield +0ms
  dat-node IMPORT ignore: /.dat/metadata.data +0ms
  dat-node IMPORT ignore: /.dat/metadata.key +1ms
  dat-node IMPORT ignore: /.dat/metadata.latest +0ms
  dat-node IMPORT ignore: /.dat/metadata.ogd +0ms
  dat-node IMPORT ignore: /.dat/metadata.signatures +1ms
  dat-node IMPORT ignore: /.dat/metadata.tree +0ms
  dat-node IMPORT skip: /dat.json +2ms
  dat-node IMPORT skip: /t.png +0ms

**Comment by millette** [comment]
Seeing this too with dat 13.11.4 and node v8.12.0.

**Comment by edsu** [comment]
I saw this as well, and upgrading to 10.x line fixed things for me too.

**Comment by christianbundy** [comment]
Confirming on Dat 13.11.4 and Node v8.15.0.

**Comment by todrobbins** [comment]
Confirming on Dat 13.11.4 and Node 8.15.1.

**Comment by dominictarr** [comment]
confirming on Dat 13.13.14 and node 8.15.0
running dat with this env prevents the problem, according to [this year old post](https://github.com/choojs/nanobus/issues/32#issuecomment-403281142)
`DISABLE_NANOTIMING=1 dat ...`

**Comment by okdistribute** [comment]
Do you still see this on dat 14.0.2 and node 12?

**Comment by todrobbins** [comment]
Working for me:

<img width="606" alt="Screen Shot 2020-03-27 at 3 32 14 PM" src="https://user-images.githubusercontent.com/158590/77802343-45d49900-7040-11ea-8e8c-2bdae643251f.png">

And in the new Beaker 😄:

<img width="727" alt="Screen Shot 2020-03-27 at 3 32 04 PM" src="https://user-images.githubusercontent.com/158590/77802385-5b49c300-7040-11ea-820e-5d3457cdaac4.png">

dat 13.13.1 (worked)
dat 14.0.2 (worked still after upgrading)
node 12

**Comment by okdistribute** [comment]
thanks @todrobbins !
