### ISSUE TITLE
GUI for usability

### ISSUE THREAD

**Issue by DonaldTsang** [datproject/dat#1043]
Since IPFS has Siderus/Orion, does Dat have GUI for it?

**Comment by pfrazee** [comment]
We have a gui in beaker that we've discussed factoring out to be potentially used in other programs, such as the dat-cli. See https://github.com/beakerbrowser/beaker/issues/1163

**Comment by G-Ray** [comment]
There is also https://github.com/dat-land/dat-desktop

**Comment by DonaldTsang** [comment]
@pfrazee I would prefer standalone client
@G-Ray thanks
