### ISSUE TITLE
Use native Object.assign instead of xtend

### ISSUE THREAD

**Issue by jimmywarting** [datproject/dat#1044]
[xtend](https://github.com/Raynos/xtend) can easily be replaced with [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

This reduce the dependencies and possible also avoid duplicated versions where some package don't use the same version range for the xtend package

```js
// immutable
Object.assign({}, a, b)

// mutable
Object.assign(a, b)
```

**Comment by joehand** [comment]
Okay, getting closer here. The leftover dependencies that use xtend are:

* dat-json
* dat-registry
* subcommand

And then Dat itself =)
