### ISSUE TITLE
How to get around China firewall?

### ISSUE THREAD

**Issue by ZhouHansen** [datproject/dat#1066]
I am reporting:

- feature request

# Bug Report

Chinese can visit google or youtube by using [shadowsocks](https://github.com/shadowsocks). But still unable to use dat. such as `dat clone` beyond local network with the shadowsocks ON.

* Operating system: macOS 10.13.6
* Node Version: 11.0.0
* Dat Version: 13.11.5

### Expected behavior

Can use dat.

### Actual behavior

Can't not use dat.

**Comment by da2x** [comment]
* Is dns.google.com blocked? Test https://dns.google.com/resolve?name=example.com
* Is the tracker blocked? Test command: `dig @discovery1.datprotocol.com TXT example.dat.local`

**Comment by joehand** [comment]
See #1082 for tracking progress.
