### ISSUE TITLE
Dat over mesh networks

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1071]
Does Dat supports local peer discovery?

**Comment by RangerMauve** [comment]
Dat makes use of [MDNS](https://en.wikipedia.org/wiki/Multicast_DNS) to find local peers on a network. Wifi networks support this, but I'm not sure what sort of mesh network you're thinking of and whether it would work.

The easiest way to get mesh networks to work is if each node in the mesh ran an DHT node from [hy[erswarm](https://github.com/hyperswarm/dht/) and you had some code automatically using them as bootstrap nodes. The thing is that there's no standard for mesh networks, so it's not something that would be worked into dat core any time soon.

The module used is [dns-discovery](https://github.com/mafintosh/dns-discovery)
