### ISSUE TITLE
[Feature] Clonning

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1073]
User can select an Dat to clone, and that can have clonning settings on json (clone.json), defining which files  can't be clonned. Also, files with -default sufix will be clonned while files with the same name but without sufix will not be clonned

**Comment by DaniellMesquita** [comment]
Also, a tree of clonned sites, like on GitHub forks.

**Comment by DaniellMesquita** [comment]
On the clonned site, user can click to upgrade it, to clone the newer files from the origin Dat. But some files on clone.json are defined as not upgradeable

**Comment by cblgh** [comment]
closing due to low effort, feel free to clarify and reopen if you think it's important though! just doing some spring cleaning :)

**Comment by DougAnderson444** [comment]
@DaniellMesquita This feature is available in beaker browser

**Comment by DaniellMesquita** [comment]
It supports parameters, such as what can be clonned, which will have its own version to clone, upgrade from the clone site, etc?

**Comment by DaniellMesquita** [comment]
Is there a wiki explaining such clonning feature?

**Comment by cblgh** [comment]
@DaniellMesquita You can read more in [this section on forking](https://beakerbrowser.com/docs/tour/#forking-or-copying-a-website) from beaker's docs. The best way to understand it is to download [Beaker](https://beakerbrowser.com/install/) and give it a try :)
