### ISSUE TITLE
How scalable is the database?

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1085]
Dat sites can have their own db and users, like Fritter. But does it supports SQL (like ZeroNet) and database sharding?

**Comment by RangerMauve** [comment]
Hi, I'm not sure what you mean by this. Dat currently has three main kinds of data structures:

- Append-only logs via Hypercore
- Key-value stores via hyperdb or hyperdrive
- kappa architecture views via stuff like kappa-core

None of these can be queried with SQL and I haven't seen any plans to create something like that. It'd be a cool use case though.

**Comment by DaniellMesquita** [comment]
SQL is faster than the Dat's db approach? How scalable it is?

**Comment by RangerMauve** [comment]
I get where you're coming from, but SQL databases and Dat are completely different technologies and have different tradeoffs and focuses.
