### ISSUE TITLE
[Question] Big file support

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1088]
Does it supports an big file to be splitted into chunks between peers?

**Comment by RangerMauve** [comment]
There's nothing out of the box for this, but it's technically possible. A contribution for this feature would be very welcome.

**Comment by DaniellMesquita** [comment]
Well, since december 2017, ZeroNet haves it implemented. Hope to get it on Dat, then it will receive better multimedia apps

**Comment by RangerMauve** [comment]
I'm not sure why splitting chunks is necessary for using Dat for multimedia. You can already serve videos and audio through a hyperdrive.

**Comment by pfrazee** [comment]
I'm pretty sure dat splits files into chunks and those chunks can be downloaded from multiple peers

**Comment by RangerMauve** [comment]
I interpreted this as sharding between peers so that a single peer doesn't need to hold all the data for a large file. Which is possible to do, but there's nothing that does it automatically.

Streaming files in chinks has been supported for a while.

**Comment by karissa** [comment]
Yes this is possible with hyperdrive but an app would have to be built to manage that. each node could request a different block range
