### ISSUE TITLE
[Feature] Add "--exit" support to "dat pull" command

### ISSUE THREAD

**Issue by joelwreed** [datproject/dat#1089]
Add a "--exit" mode to "dat pull" that such that pull could check for like, 5-10 seconds, and if no changes have been made to the repo, the process would exit. This would allow dat to better support scenarios involving cronjobs or other automated periodic update scenarios.

Currently, "--exit" does not effect the behavior of "dat pull" in any noticeable way. Here's a windows example:

![image](https://user-images.githubusercontent.com/100404/55248104-7ca28400-521f-11e9-91dd-6942f13a8c99.png)

**Comment by joelwreed** [comment]
This is related to #892.

Offending line is at https://github.com/datproject/dat/blob/e24d8d349e459927a0f36bdaaebf815a3fe3cccc/src/lib/download.js#L35

**Comment by karissa** [comment]
Yes, this issue arrises when the dat is already in sync and there are no new updates, so `state.download.modified` is false

**Comment by joelwreed** [comment]
One other note: "[dat-cp](https://github.com/tom-james-watson/dat-cp)" can be a good alternative until this addressed.

**Comment by joehand** [comment]
Released in `13.13.0`
