### ISSUE TITLE
Is it possible to "dat" a .tar.gz file, but version inside it?

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1107]
Not good to version a binary, but its inner contents.

**Comment by RangerMauve** [comment]
You might be able to do something like that once the new hyperdrive changes land and give you the ability to modify the internals of a file. Feel free to experiment with it in the hyperdrive API. :)

**Comment by DaniellMesquita** [comment]
Suggested it to IPFS/Pando:
https://github.com/pandonetwork/pando/issues/55

**Comment by DaniellMesquita** [comment]
I'm asking that because I have a usecase for it:
https://usv.js.org/

Is a versionable video format in .tar.gz compression.

**Comment by joehand** [comment]
You can do this with the hyperdrive API. See https://github.com/joehand/tar-dat (outdated but will show you how)
