### ISSUE TITLE
[Question] Alongside ignore function, can it haves optional files, that are only downloaded when request?

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1108]
ZeroNet haves a option to not automatically download some files from a site, which are downloaded when requested, such as images and other media.

**Comment by DougAnderson444** [comment]
@DaniellMesquita **Are you reading the docs?**  When you read the documentation, you will see the `sparse` option. 
[https://github.com/datproject/dat-node#download-on-demand](https://github.com/datproject/dat-node#download-on-demand)

```
const opts = {
  key: 'a key',
  sparse: true,
};

Dat(dir, opts, cb)
```
