### ISSUE TITLE
Sodium Native Error on Mac OSX

### ISSUE THREAD

**Issue by dmitriz** [datproject/dat#1110]
I am reporting:

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: Mac OS 10.8.5
* Node Version: v10.15.3
* Dat Version: dat@13.13.0

### Actual behavior

Running `dat share ne` generates errors:

```sh
→ dat share ne
dyld: lazy symbol binding failed: Symbol not found: _memset_s
  Referenced from: /Users/dmitrizaitsev/.npm-global/lib/node_modules/dat/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _memset_s
  Referenced from: /Users/dmitrizaitsev/.npm-global/lib/node_modules/dat/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

### Debug Logs

```sh
→ DEBUG=dat* dat share ne
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.13.0 +7ms
  dat node v10.15.3 +0ms
  dat Sharing archive { _: [ 'ne' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  watch: true,
  logspeed: 400,
  dir: 'ne' } +0ms
dyld: lazy symbol binding failed: Symbol not found: _memset_s
  Referenced from: /Users/dmitrizaitsev/.npm-global/lib/node_modules/dat/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _memset_s
  Referenced from: /Users/dmitrizaitsev/.npm-global/lib/node_modules/dat/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

```

**Comment by karissa** [comment]
Can you try reinstalling dat? And also perhaps try using node 8?

**Comment by aral** [comment]
Does Dat not support Node LTS at the moment?

Aral

**Comment by emilbayes** [comment]
@dmitriz This is because you are on an OS that doesn't have the `memset_s` function in the stdlib. You macOS is unsupported from Apple also :) You may be able to update your libc and get it to work anyway

**Comment by mafintosh** [comment]
@aral 10 is fine, i think we need to update sodium for 12 tho.

**Comment by dmitriz** [comment]
> @dmitriz This is because you are on an OS that doesn't have the memset_s function in the stdlib. You macOS is unsupported from Apple also :) You may be able to update your libc and get it to work anyway

Sounds like a major task, is it simple/safe? 
I was hoping such open project would help community to lower its dependence on private corporations such as Apple :)

**Comment by aral** [comment]
@dmitriz Fire up your Linux machine and run DAT on that (I do). DAT is in no way limited to Apple’s platforms. Running the latest version of your operating system is just a basic security practice and no project has the resources to support older versions of multiple operating systems as infinitum. Hope you get it running and enjoy using DAT.

**Comment by dmitriz** [comment]
> @dmitriz Fire up your Linux machine and run DAT on that (I do) :) DAT is in no way limited to Apple’s platforms. Running the latest version of your operating system is just a basic security practice and no project has the resources to support older versions of multiple operating systems ad infinitum. Hope you get it running and enjoy using DAT.

Fair enough. Just wanted to report my error here to help others rather than try it myself if that requires any major time investment and risk... such as running updates to slow down my computer, as happened to my other Macs... the change in performance was massive, a lesson not to repeat :).

**Comment by emilbayes** [comment]
@dmitriz It's not as much about Apple as it is an update to your standard library. It may be possible to do on your own without upgrading the OS, but I don't know how. Sometimes you also have to assume so basic level of support :) The function in question is a secure way to wipe sensitive material and we can't support systems that don't have it. `memset_s` was introduced with the C11 standard

**Comment by joehand** [comment]
Can we close this?

**Comment by joehand** [comment]
I guess we will keep it open until Sodium native on node 12 is supported =) 

https://github.com/sodium-friends/sodium-native/issues/95

**Comment by emilbayes** [comment]
@joehand technically this doesn’t make a difference for *this* issue, but the title is otherwise correct in that regard :)

**Comment by joehand** [comment]
Hahaha ya oops.

**Comment by karissa** [comment]
This should be fixed now by the [latest sodium-native release.
](
https://github.com/sodium-friends/sodium-native) Can someone verify if anything else needs to be done so that the CLI works seamlessly on node 12?

**Comment by emilbayes** [comment]
@karissa Yeah, build is a bit borked for now. We're trying to fix it

**Comment by emilbayes** [comment]
Everything is back to normal now. https://github.com/sodium-friends/sodium-native-citgm

**Comment by karissa** [comment]
Amazing!! Nice work 😊
