### ISSUE TITLE
dat transfer freeze

### ISSUE THREAD

**Issue by dustiestgolf** [datproject/dat#1114]
I am reporting: unexpected behavior

# Bug Report

originator -  using CLI on linux
peer -  installed dat-desktop on mac using .dmg 

* Operating system:
o - Ubuntu 18.04
p - OSX
* Node Version: 
o - v12.3.1
p - (whatever came in dat-desktop .dmg)
* Dat Version:
o - v13.13.1
p - (whatever came in dat-desktop .dmg)

### Expected behavior

Once a dat connects to its first peer it should stay connected until the files sync as long as both users continue to have dat open. 

### Actual behavior

I created the dat with `dat share path/to/file/`and sent the link to my peer. They input the link in the dat-desktop application. Initially peers connected. I saw 1 connection appear and transfer began. At about 20% transfer peer connection was lost. We have both tried quitting and starting dat on both ends but the connection has not been reestablished. 

### Debug Logs

I cant get dat to reconnect to the peer again to recreate the behaviour of it losing the peer mid transfer. Will update if I can.
```
```

**Comment by RangerMauve** [comment]
Might be an issue with dat-desktop. That hasn't been updated in a while. Does the cli or Beaker work for them? What sort of network are the two sides on?

**Comment by dustiestgolf** [comment]
Both are home networks. I had them use dat-desktop because they're less technically savvy and I have to communicate through text messages. Beaker could work, I'll try to move forward with that instead.

**Comment by dustiestgolf** [comment]
Beaker works. Must be something with desktop.
