### ISSUE TITLE
Dat already supports UnwalledGarden standards or it will depend on Beaker 0.9?

### ISSUE THREAD

**Issue by DaniellMesquita** [datproject/dat#1118]

**Comment by pfrazee** [comment]
Depends on what kind of support youre looking for. UnwalledGarden is all just files, so any dat client can read the files. If you're looking for the queryable indexes, you'll need something like beaker 0.9

**Comment by pfrazee** [comment]
Didnt mean to close the issue

**Comment by DaniellMesquita** [comment]
@pfrazee could I manually create a Dat compatible with UnwalledGarden? As I've heard it will have two types, public and private.

**Comment by pfrazee** [comment]
Yeah, you can. The public and private refer to two dats that represent the user's filesystem, a public dat and a private dat.

**Comment by DaniellMesquita** [comment]
@pfrazee So, I could just manually create a public dat compatible with, and later when UnwalledGarden is launched, link it with a private counterpart?

What is the direct script (that replies a output) used to name posts when they're posted? And their inner data scheme?

**Comment by DaniellMesquita** [comment]
@pfrazee
> If you're looking for the queryable indexes, you'll need something like beaker 0.9

So, a dat-node based app will need Beaker for queryable indexes?

**Comment by pfrazee** [comment]
No you just need those queryable indexes to be implemented somewhere. Beaker is one place. If you're not using beaker then you'll need to build them on your own.

**Comment by DaniellMesquita** [comment]
> No you just need those queryable indexes to be implemented somewhere. Beaker is one place. If you're not using beaker then you'll need to build them on your own.

But it could be implemented in dat-node, which I think Beaker uses.

**Comment by DaniellMesquita** [comment]
@RangerMauve 
Would you implement UG in Dat SDK?

**Comment by RangerMauve** [comment]
@DaniellMesquita Not any time soon. 😅 There's a lot of work to do in just getting Hyperdrive working across platforms. But it shouldn't be too hard to implement it on top of the SDK.
