### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by oijkhg** [datproject/dat#1120]
**Feature**: Add i2p support to DAT
**Why?**: Mainly for privacy and security but also to support decentralized web communications.
**How?**: BitTorrent already has wide usage of i2p thank to i2p-snarks and [XD](https://xd-torrent.github.io/).
____________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75581012-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75581012)](https://www.bountysource.com/issues/75581012-feature-support-i2p)

**Comment by RangerMauve** [comment]
I'd love to play around with this. Is there a Node.js implementation of i2p?

Getting java into our stack would be a big no-no, and I'm not sure how much effort it'd be to add a C++ library to play nice with everything.

I think once we get the Daemon and SDK set up, it'd be easier to start thinking about anonymity and stuff. Funding for such research would of course be welcome. :)

**Comment by DaniellMesquita** [comment]
Personally I'm not in favour of Dat having a Daemon version.
If you talk about i2p, eh, it could be spawned from Dat's JS and communicate through RPC.

**Comment by joehand** [comment]
This issue was moved to https://dat.discourse.group/t/feature-support-i2p/62
