### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by andrepopovitch** [datproject/dat#1131]
I am reporting: a bug or unexpected behavior

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: MacOS 10.14.5
* Node Version: v12.1.0
* Dat Version: N/A

### Expected behavior

When I run `npm install -g dat`, dat should be installed to my computer

### Actual behavior

I get this error: https://pastebin.com/BhbgU3mf

**Comment by joehand** [comment]
See #1110
