### ISSUE TITLE
Dependancies

### ISSUE THREAD

**Issue by mikegeoffrey** [datproject/dat#1137]
I am reporting:
- general feedback

Using http://npm.anvaka.com/#/view/2d/dat dat v13.13.1 has a dependency tree of 435 modules.  WIll the dat project focus any effort on reviewing these and removing where possible?

**Comment by joehand** [comment]
We've put some effort to remove unneeded dependencies such as #1044, #850, and others. If you see specific dependencies that are not needed or could be better served by an alternative please open a more specific issue. I am happy that there are 435 great modules we can depend on to make this software possible =)
