### ISSUE TITLE
[Feature Request]Use dat icon in binary

### ISSUE THREAD

**Issue by linsui** [datproject/dat#1143]
I am reporting:
feature request

Could you please use dat's icon instead the icon of nodejs in binaries? The file metadata should be changed, too.

**Comment by RangerMauve** [comment]
Would you be interested in submitting a PR for this change?

We're using the [pkg](https://www.npmjs.com/package/pkg) module for the builds

**Comment by linsui** [comment]
Sorry, I'm not a developer...

**Comment by linsui** [comment]
Close since dat is unmaintained.
