### ISSUE TITLE
[Feature Request] Checksum for binaries

### ISSUE THREAD

**Issue by linsui** [datproject/dat#1144]
I am reporting:
feature request

Could you please publish checksum for binaries?

**Comment by RangerMauve** [comment]
Where should the checksum be published? Along side the GH downloads page?

Wouldn't anybody faking the downloads also be able to fake the checksum?

**Comment by linsui** [comment]
It can be published on both of download page and homepage. It can also be used to check if file is broken when downloading.

**Comment by linsui** [comment]
Close since dat is unmaintained.
