### ISSUE TITLE
Broken images in the readme

### ISSUE THREAD

**Issue by Frijol** [datproject/dat#1148]
I am reporting:
- a bug or unexpected behavior

# Bug Report

Broken images in the readme to this repo!

![Screen Shot 2019-08-30 at 2 43 44 PM](https://user-images.githubusercontent.com/454690/64052805-c11aae80-cb34-11e9-8514-a512116ff404.png)

Need re-linking

**Comment by RangerMauve** [comment]
Oof, I think the docs in general are going to need an overhaul. 😅 cc @whoisgina

**Comment by okdistribute** [comment]
Fixed
