### ISSUE TITLE
only `dat` file in /.well-known/ directory is shared/synced

### ISSUE THREAD

**Issue by dym-sh** [datproject/dat#1154]
no reason to restrict those imo,
some keep pgp-keys in there
and other contact~ish information

atm im experimenting with dat being my deploy tool for a website (static files only),
and having some of them just be ignored w/o notice is very frustrating

**Comment by RangerMauve** [comment]
Hey, thank you for the heads up!

What version of the CLI are you using?

Also, do you have a `.datignore` file in the folder?

Looking into the [source for dat-ignore](https://github.com/datproject/dat-ignore/blob/master/index.js#L22) it doesn't seem like it should be doing anything special with the `.well-known` directory.

**Comment by dym-sh** [comment]
version: latest stable from npm

> standard .datignore:
```
.git
.dat
node_modules
*.log
**/.DS_Store
Thumbs.db
```

full contents of `/.well-known/`:
https://github.com/dym-sh/site/tree/master/.well-known

i also made new pure dat with _only_ `/.well-known/`, and the problem repeated itself

**Comment by dym-sh** [comment]
ohwait, it's [_white-listing_](https://github.com/datproject/dat-ignore/blob/master/index.js#L15) only the `dat` file!

**Comment by dym-sh** [comment]
imo, if there is a `.datignore` -- everything _not_ in there should be included.

**Comment by RangerMauve** [comment]
Are you using `dat share` on one machine and using `dat sync` on another machine? It should be including anything that's not in the datignore file.

**Comment by RangerMauve** [comment]
Do you happen to be loading this archive through dat-gateway or hashbase?

**Comment by dym-sh** [comment]
yes, share/sync, and sync/sync later yield the same.

you can see all the files on source: https://github.com/dym-sh/site

hashbase is only a secondary sync target, it didnt matter, files are missing on my server

and as i said, i created a new dat (no hashbase) with just `.well-known/`, and the `dat` file was the only one shared.

try to put random files in .well-known and see if they sync.

**Comment by RangerMauve** [comment]
I think I found it! By default, the CLI has the `ignoreHidden` flag set to `true` which means it'll ignore any folders that start with a `.`. When doing a share or sync, you should set this flag to false and manually add any "hidden" folders to the `.datignore` file. 

So unless I'm mistaken about the boolean parsing logic, you should be able to do something like this:

```
dat share . --ignoreHidden=false
```

Refs:

https://www.npmjs.com/package/dat-ignore#options

https://github.com/datproject/dat-node/blob/master/dat.js#L109

https://github.com/datproject/dat/blob/master/src/commands/share.js#L18

**Comment by dym-sh** [comment]
alright, [it worked](https://dym.sh/.well-known/) :D

will have to alias `dat sync --ignoreHidden=false`
