### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by okdistribute** [datproject/dat#1176]
Stop using request.

**Comment by aral** [comment]
I’ve been using bent (spiritual successor to request, also by Mikael). If it fits the bill, would recommend.

**Comment by RangerMauve** [comment]
I've been using node-fetch so that my code can be more portable to browsers. 😁 https://www.npmjs.com/package/node-fetch

**Comment by millette** [comment]
Seems like `request` is only used in the `nets` package, which depends on `xhr` for the browser, and `request` for node.

```sh
npm install dat@next
npm ls request
didi@0.0.0 /home/millette/didi
└─┬ dat@14.0.2
  └─┬ dat-registry@4.0.1
    └─┬ nets@3.2.0
      └── request@2.88.2 
```

`isomorphic-fetch` (4 years old) and `isomorphic-unfetch` (2 years old) both provide a package similar to `nets`, but depend on `node-fetch`.

There are other uses of `request` but only in tests and I don't think those have to work in both browser and node environments.

**Comment by joshterrill** [comment]
@okdistribute this issue can be closed as https://github.com/datproject/dat/pull/1198 was merged.
