### ISSUE TITLE
Link to Dat Desktop in README.md is incorrect.

### ISSUE THREAD

**Issue by ryliejamesthomas** [datproject/dat#1178]
Just noticed that the link to the Dat Desktop application provided in the readme (see:  https://github.com/datproject/dat#desktop-applications) points to an anchor that doesn't exist, on a page without the relevant information.

Currently: https://docs.datproject.org/install#desktop-application
Should be: https://github.com/datproject/dat-desktop ?

**Comment by RangerMauve** [comment]
Good catch. Would you be up for submitting a pull request with the change? 😁

**Comment by ryliejamesthomas** [comment]
Yep, no worries!

**Comment by RangerMauve** [comment]
Thank you!
