### ISSUE TITLE
fix tests on windows CI

### ISSUE THREAD

**Issue by maxogden** [datproject/dat#185]
I do not know why, but appveyor has some [failing CLI tests on windows](https://ci.appveyor.com/project/maxogden/dat/build/322) but the same tests pass when I run them on windows XP in virtualbox (in both git-shell and CMD.exe)

appveyor uses windows server 2008

![screen shot 2014-09-14 at 4 03 22 pm](https://cloud.githubusercontent.com/assets/39759/4265857/859b4afa-3c63-11e4-9871-a14de7242179.png)

**Comment by karissa** [comment]
it'd be nice if we had windows support for beta

**Comment by karissa** [comment]
We're going to postpone guaranteeing windows compatibility until 1.0

**Comment by onbjerg** [comment]
Hey, could maybe be a diff in the MSVC versions. Can you check on your VM and set the version on Appveyor? [It seems you can set it somehow](https://www.appveyor.com/docs/installed-software#visual-studio).

It could be it, since it's msbuild that's failing for libutp in the package utp-native.

**Comment by karissa** [comment]
@mafintosh did you need windows support for the contract you were working on? curious what's left

**Comment by joehand** [comment]
<img width="403" alt="screen shot 2017-10-19 at 12 26 23 pm" src="https://user-images.githubusercontent.com/684965/31789977-bd5dea66-b4c8-11e7-9f87-1b6a50b93c12.png">


woot! all green: https://ci.appveyor.com/project/joehand/dat/build/1.0.45
