### ISSUE TITLE
RC2 Known Issues

### ISSUE THREAD

**Issue by joehand** [datproject/dat#486]
## Sharing/Uploading

- [x] Live mode doesn't recursively update files
- [x] Resuming live mode does not include files updated since last run (this is related to the mtime bug, will wait for hyperdrive-import-files).

## Downloading

- [ ] % and Size can be greater than total ([img](https://usercontent.irccloud-cdn.com/file/ZEiNV4JQ/Screen%20Shot%202016-06-17%20at%2011.56.56%20AM.png))
- [ ] Empty Files/Directories not downloaded to file system (https://github.com/mafintosh/hyperdrive/issues/28)
- [x] Download speed should zero right after finishing.
- [x] Add message for download complete

## General

- [ ] not clear when things are being resumed vs started new
- [ ] Improve previously downloaded error message
- [x] [networking troubleshooting info](https://github.com/maxogden/dat/issues/503#issuecomment-237254932)
- [x] document doctor

**Comment by joehand** [comment]
Improve error message for dat previously downloaded. Should at least remove the stack trace.
```
Starting Dat...

Connecting...
Error: Dat previously downloaded. Run dat 2pv5p5b6qk14cg5001phl1i8nxjqfz03k8yofn07vtn7ziie07 to resume
    at /Users/joe/node_modules/dat/lib/dat.js:94:10
    at apply (/Users/joe/node_modules/dat/node_modules/thunky/index.js:16:28)
    at /Users/joe/node_modules/dat/node_modules/thunky/index.js:20:25
    at apply (/Users/joe/node_modules/dat/node_modules/thunky/index.js:16:28)
    at /Users/joe/node_modules/dat/node_modules/thunky/index.js:20:25
    at done (/Users/joe/node_modules/dat/node_modules/hypercore/lib/feed.js:646:5)
    at Storage.open (/Users/joe/node_modules/dat/node_modules/hypercore/lib/storage.js:13:8)
    at openStorage (/Users/joe/node_modules/dat/node_modules/hypercore/lib/feed.js:638:18)
    at loop (/Users/joe/node_modules/dat/node_modules/hypercore/lib/feed.js:628:14)
    at /Users/joe/node_modules/dat/node_modules/levelup/lib/levelup.js:230:7
```

**Comment by joehand** [comment]
Closing this since we finished most of these. I'd be easier to track these one by one.

**Comment by karissa** [comment]
wooT!
