### ISSUE TITLE
integrate DAT into an existing node application ?

### ISSUE THREAD

**Issue by fredhampton** [datproject/dat#505]
We would like to integrate DAT into an existing node application and are hopeful that you can point us in the right direction.

Is it possible to integrate DAT into an existing node application ?
Our current node application is distributed using electron so we would need to integrate into our current node app and then build the final Electron distro.

**Comment by juliangruber** [comment]
Yes this is absolutely possible! You can either to the manual route and patch up modules hyperdrive, dat-encoding, hyperdrive-archive-swarm, random-access-file and level for maximum flexibility, or use one of convenience wrappers like https://github.com/joehand/dat-js.

**Comment by fredhampton** [comment]
Thanks so much for your help !!!!
We very much like the current U.I. from the DAT OS X Electron Distro.
All of our users are using OS X and our current app is in an Electron Distro for OS X
Would it be possible to integrate the U.I. as well as the functionality into our current node app and then to create the Electron Disto ?


All thanks to you !!!

 

On August 24, 2016 at 8:37:01 AM, Julian Gruber (notifications@github.com) wrote:

Yes this is absolutely possible! You can either to the manual route and patch up modules hyperdrive, dat-encoding, hyperdrive-archive-swarm, random-access-file and level for maximum flexibility, or use one of convenience wrappers like https://github.com/joehand/dat-js.

**Comment by joehand** [comment]
Our file browsing UI module is [hyperdrive-ui](https://github.com/karissa/hyperdrive-ui) which we use in the dat-desktop app. You could use that module in the same way in your app. 

You can use also use Dat in an electron app without using our UI modules, for example the [beaker browser](https://github.com/pfraze/beaker) is doing this and has a similar file browsing UI. The Dat part is in a [plugin](https://github.com/pfrazee/beaker-plugin-dat).

**Comment by fredhampton** [comment]
Got it !!! 
We want to add a link to our menu for DAT and have it open inside of our application…We are wanting to use the desktop version of DAT so that each users can leverage there system. Is there a way to do this …..?   In this scenario a user would download our apps as an Electron disto …..When they were using it they could click on a link item “DAT" and then in the center page of the our app the DAT app would show 


All thanks to you !!!!

 

On August 24, 2016 at 11:01:00 AM, Joe Hand (notifications@github.com) wrote:

Our file browsing UI module is hyperdrive-ui which we use in the dat-desktop app. You could use that module in the same way in your app.

You can use also use Dat in an electron app without using our UI modules, for example the beaker browser is doing this and has a similar file browsing UI. The Dat part is in a plugin.
