### ISSUE TITLE
doesn't finish updating file

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat#511]
I hit a dat bug (?) where it doesn't finish updating a file.

Steps to reproduce:

1. In terminal 1, create and share a dat:

  ![screen shot 2016-09-02 at 08 31 02](https://cloud.githubusercontent.com/assets/10247/18194668/9a51e430-70e7-11e6-9eae-a841a7f59f0c.png)

2. In terminal 2, download the dat, then quit:

  ![screen shot 2016-09-02 at 08 31 42](https://cloud.githubusercontent.com/assets/10247/18194683/b199e822-70e7-11e6-8624-9d6b4e23d651.png)

3. In terminal 1, stop seeding, update the file, and start seeding again:

  ![screen shot 2016-09-02 at 08 32 06](https://cloud.githubusercontent.com/assets/10247/18194690/c0336282-70e7-11e6-8ab7-30befee3dc0e.png)

4. In terminal 2, sync the dat again:

  ![screen shot 2016-09-02 at 08 32 29](https://cloud.githubusercontent.com/assets/10247/18194699/ccf02906-70e7-11e6-9fb3-ab4099cb59be.png)

Quitting the process after some time, the file contents haven't yet changed.

Is this something that we don't support, or don't support yet? Am I required to create a new dat for this?

**Comment by joehand** [comment]
We do support this, looks like a bug. I can take a look today.

**Comment by karissa** [comment]
aye yeah, pretty critical ! D:

**Comment by joehand** [comment]
Current Dat CLI does not track mtime changes (it doesn't use hyperdrive-import-files). This is fixed in PR #509, so we should try to get that released soon.

**Comment by joehand** [comment]
This should be fixed on master now.

**Comment by juliangruber** [comment]
tested and works! great work @joehand :)
