### ISSUE TITLE
Improve UX for Resuming Old Dat

### ISSUE THREAD

**Issue by joehand** [datproject/dat#513]
Make it clear when you are resuming a previously created Dat (share or download).

**Comment by juliangruber** [comment]
also would be cool: `dat resume dl/`

**Comment by karissa** [comment]
i think a person shouldn't have to know whether or not it was a dat already, because you're still just sharing folder contents and getting the link.

**Comment by karissa** [comment]
You can just do `dat <folder>` now and it'll resume for you
