### ISSUE TITLE
show past progress before a peer connects

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat#515]
<img width="941" alt="screen shot 2016-09-07 at 10 08 05" src="https://cloud.githubusercontent.com/assets/10247/18304507/033f44ac-74e3-11e6-8b01-c7eb0cdb4917.png">

I've downloaded parts of this before. Even though there's no peer yet, it should know how much has been downloaded already, right?

**Comment by joehand** [comment]
Yep. 

Also, the same bug makes it so if you download the whole thing and restart, it'll keep saying "Starting Dat" even if you connect to peers.

**Comment by joehand** [comment]
Unfortunately, this is not as straightforward as I thought without persisting the stats. I think rather than rewriting how existing stats work, we should do this with hyperdrive-stats integration.

**Comment by karissa** [comment]
OK, +1 on closing this then
