### ISSUE TITLE
Temporary in-memory dats

### ISSUE THREAD

**Issue by pfrazee** [datproject/dat#516]
I have a workflow where I need to create temporary dats. The flow is, I want to work on a dat site, so I need the files to be hosted, but I dont want the changes to get recorded in the dat's history.

So, ideally, could do something like

```
dat . --temp
```

And it would create a dat in-memory, leaving `./.dat` alone.

**Comment by joehand** [comment]
Ya this would actually be very simple to implement. The only hesitation is adding memdb as a main dependency. Let me try using slow-deps to see how much that'd add.

**Comment by joehand** [comment]
memdb adds 5 seconds (2 min total) and ~700 KB (49 MB total). What do y'all think? Worth it?

**Comment by ryanramage** [comment]
What about not adding memdb as a dependency, but prompting the user if they do the --temp option and memdb is not available that they run npm i memdb.

Another option: (more radical, but user friendly) is https://www.npmjs.com/package/lazy-require

**Comment by pfrazee** [comment]
Or, instead of memdb, using /tmp ?

**Comment by ryanramage** [comment]
--memdb or --storage=/path/to/storage as other suggested options.

**Comment by joehand** [comment]
Well I added `--temp` in #519. The other alternative that sounds good would be `--dbPath=/tmp` or something similar.

Lazy require adds bigger overhead than memdb so unless we use it for other modules, that'd not be the best way forward.

Requiring user to install memdb later would not be straightforward for global packages. I think you'd either have to global install memdb or install in the global dat package. And we wouldn't have any way to require a specific version.

**Comment by pfrazee** [comment]
Thanks @joehand! The added overhead sucks but isn't the *absolute* worst. The feature is very useful.

**Comment by joehand** [comment]
Ya, I think this makes sense. A `db path` option would be much harder to understand/use.

**Comment by joehand** [comment]
Published `--temp` in 11.2.0

**Comment by pfrazee** [comment]
Thanks @joehand !
