### ISSUE TITLE
File is not re-synced if it was deleted or modified in target directory

### ISSUE THREAD

**Issue by maxalbert** [datproject/dat#518]
## Steps to reproduce

(i) Create a text file in the source directory `A/` and share it with dat.

``` bash
$ mkdir A/
$ cd A/
$ echo "Hello world" > foobar.txt
$ dat .
```

(ii) In a separate terminal, create the target directory `B/` and download the files. This syncs the file correctly, as expected.

``` bash
$ mkdir B/
$ cd B/
$ dat <dat-link> .
$ cat foobar.txt
Hello world
```

(iii) Now modify (or remove) the file in the target directory.

```
$ echo "quux" > B/foobar.txt
$ cat B/foobar.txt
quux
```
## Expected behaviour

I'd expect the contents of `B/foobar.txt` to be re-synced so that they reflect the version in `A/foobar.txt`, because my understanding is that `A/` is the "definitive source" and so long as the two directories are synced I'm effectively saying that `B/` should always reflect the contents of `A/`.
## Actual behaviour

What currently happens is that `B/foobar.txt` is not updated. _However_, as soon as I modify `A/foobar.txt` (or even just update its filestamp using `touch`), it gets re-synced.

One might argue that in the case of file modifications there is ambiguity whether files in `B/` should just be overwritten without warning (although as a user I'd expect this because the directories are synced - effectively, I'm expecting unidirectional Dropbox-like behaviour A -> B).

However, `dat` shows the same behaviour if `B/foobar.txt` is _deleted_ instead of modified: even if `dat` is actively syncing the two directories the deleted file does not re-appear in `B/` until it is modified in `A/` (or its timestamp updated). From a user's point of view this is very unintuitive because there is no potential for conflict in this case, and `dat` is apparently actively syncing the two directories.

I presume this is a bug, but please let me know if I misunderstood something in the way in which `dat` is supposed to work.
## Versions

I am using dat installed from source (latest master; git rev. a7ff2014452397077da0d0016d3807dab9422570)

```
$ dat --version
11.1.2

$ node --version
v4.5.0

$ npm --version
2.15.9

$ nvm --version
0.31.7
```

**Comment by joehand** [comment]
This depends on [hyperdrive issue 97](https://github.com/mafintosh/hyperdrive/issues/97). To fix this we'll have to watch files on the download side.

> One might argue that in the case of file modifications there is ambiguity whether files in B/ should just be overwritten without warning (although as a user I'd expect this because the directories are synced - effectively, I'm expecting unidirectional Dropbox-like behaviour A -> B).

Ya this is a big question. I'd imagine force syncing changes could be confusing. But you are right that "A" should be the source.

Delete and re-sync will be a bit less of a user experience issue, so we could start with implementing that.

**Comment by juliangruber** [comment]
This will also be less of an issue once we have snapshots implemented, in which case we might design the cli so you need to opt-in to receiving file updates

**Comment by karissa** [comment]
We don't want to force the downloader to always be at the latest state because we plan on implementing history and log, so you will be able to see how your current version differs from the history/latest in the swarm. This is useful for people who also want to 'pause' or try new things out in their copy of the data.

We could add a command to 'force to latest' or something like that to wipe your local changes and sync to exactly what the remote has. Would this solve the issue for you?
