### ISSUE TITLE
Use dat.json file and use title field for directory

### ISSUE THREAD

**Issue by joehand** [datproject/dat#522]
Use [dat.json](https://github.com/juliangruber/dat.json). Title will be the directory name.
## Share
- [ ] Create `dat.json` file on new share
- [ ] Write directory name to `dat.json` as title
- [ ](optional) Make name pretty from dir name
## Download
- [ ] Make download directory optional argument
- [ ] Download to directory with name as title if dir not specified (like `git clone`)
- Other metadata info can be edited by hand (including title, later). Would rather not add other metadata related features until spec is a bit more developed.
- Make sure `dat.json` is not created with `--temp` argument.

**Comment by karissa** [comment]
This is sort of like `dat init`

**Comment by joehand** [comment]
This will not be implemented with this version. We can reconsider this feature on dat-next.
