### ISSUE TITLE
Share folder twice, progress size is larger than total

### ISSUE THREAD

**Issue by joehand** [datproject/dat#523]
If you share a folder, the progress size is double what it should be.

[screenshot](https://www.dropbox.com/s/ajkqd5kb1jw522b/Screenshot%202016-09-15%2020.47.25.png)

**Comment by joehand** [comment]
This is an issue with [hyperdrive-import-files](https://github.com/juliangruber/hyperdrive-import-files). 

If, for some reason, the archive gets duplicate entries then the size progress may end up doubled. I started to fix this in [this PR](https://github.com/juliangruber/hyperdrive-import-files/pull/14) but we had to fix the mtime issues first. I can go back and take a refreshed look at that now that we have resume/live working correctly. 

[This line](https://github.com/juliangruber/hyperdrive-import-files/blob/master/index.js#L122) is the cause.

**Comment by karissa** [comment]
if `list` is the new list instead of the entire history would this be fixed?

**Comment by joehand** [comment]
No, this is happening on the file import, before we can use `archive.list`.  This is kind of two issues:

1. duplicates are getting added somewhere (I think this may be an issue with old `.dat` folders missing the `mtime` in the metadata).
2. the totalSize is not reflecting what is in directory.

That will help fix some other counting bugs though =).

**Comment by joehand** [comment]
The UI for this is improved. Other bugs related include the watch bug and adding file duplicates which we are addressing elsewhere.
