### ISSUE TITLE
Too many Files Being Watched (EMFILE)

### ISSUE THREAD

**Issue by beingalink** [datproject/dat#524]
I get following error message on my vps after seeding a folder for a while:

`Error: EMFILE: too many open files, open '/home/thelink/tmp/data-science-workshop/.git/objects/pack/pack-7565db57393c53df693cc4711d82f8727b550205.pack' at Error (native)`

My VPS is on CentOS 7
Dat Cli 11.2.0
node 4.5.0

**Comment by joehand** [comment]
This is from watching all the files w/ [chokidar](https://github.com/paulmillr/chokidar). A bit of good reading on this [here](https://github.com/paulmillr/chokidar/issues/141) and [here](https://github.com/substack/node-browserify/issues/431). 

@beingalink you could increase the ulimit for now: `ulimit -n 2560`. 

This is a good reason to ignore hidden directories by default though.

**Comment by pfrazee** [comment]
I just had something kind of like this. I wanted to test beaker's reaction to a big addition to an actively-syncing dat. So I had a live dat going, and I copied the beaker source into it. 818MB, so not too huge, but a *lot* of files.

The copy thread took too long and the dat cli process wasnt updating its stats, so I closed the dat process. After a few moments, it closed, and the cp thread aborted with a lot of errors that looked like this:

```
...
cp: /Users/paulfrazee/my/beaker-browser//node_modules/y18n: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yallist: unable to copy extended attributes to ./beaker/node_modules/yallist: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yallist: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yargs: unable to copy extended attributes to ./beaker/node_modules/yargs: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yargs: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yargs-parser: unable to copy extended attributes to ./beaker/node_modules/yargs-parser: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yargs-parser: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yauzl: unable to copy extended attributes to ./beaker/node_modules/yauzl: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/yauzl: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/zip-stream: unable to copy extended attributes to ./beaker/node_modules/zip-stream: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//node_modules/zip-stream: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//package.json: Too many open files
cp: /Users/paulfrazee/my/beaker-browser//README.md: Too many open files
...
```

**Comment by juliangruber** [comment]
I think @mafintosh suggested doing scans for changes instead of continuously watching for fs events. This will arguably get us around this problem, however it's potentially a lot slower. With small trees you'll notice more lag, with big trees the scans will

1) take long
2) wake up the hd on a laptop
3) in general cause seeks that will drain battery

While it's tempting to say "works is more important than works fast", a system that's too slow to be practical will also not have any real use.

**Comment by pfrazee** [comment]
This is challenging. FS watching has always been problematic due to OS issues. We should consider whether watching is going to be reliable enough to use alone, or if it should be an optional mode

**Comment by karissa** [comment]
I can investigate this a bit and see if its a matter of replacing that library or something
