### ISSUE TITLE
'another dat already downloaded here' confusing

### ISSUE THREAD

**Issue by karissa** [datproject/dat#531]
During user testing, someone tried to download a different dat into the same folder and was really confused by the output. They didn't know what they had done wrong. I had to walk them through removing the `.dat` folder. They didn't know how to `ls -a` or to `rm -rf .dat` so it was a bit of a painful experience. 

I suggest having better output here. It'd also be nice to have a `dat clean` or `dat rm` command or something that would clean up the dat

**Comment by karissa** [comment]
`fatal: destination path 'dat' already exists and is not an empty directory.` is what git does. Maybe being more specific will be helpful

**Comment by joehand** [comment]
PR for this fix is in [dat-js](https://github.com/datproject/dat-js/pull/40)

**Comment by joehand** [comment]
Released in 11.6.0
