### ISSUE TITLE
When can't connect to BitTorrent DHT, other methods aren't working either.

### ISSUE THREAD

**Issue by karissa** [datproject/dat#532]
### Repro
1. share a directory
2. open a new terminal and download the directory
3. they can't find eachother.
4. turn off wifi
5. re-share, re-download
6. they find eachother.

Output during step 3 seems like its trying to reach the bittorrent dht and failing. But it should still be trying to find the local dat using another mthod, right? This person also wasn't able to successfully use other programs that relied on the bittorrent dht, like utorrent and transmission.

dat doctor output
https://gist.github.com/baruchlab/5a101bc8d47c2263fae79809c85e4892

**Comment by karissa** [comment]
found by @baruchlab

**Comment by bcomnes** [comment]
I think I've run into cases where dats intermittently won't find each other.

**Comment by mafintosh** [comment]
@karissa that doesn't look like doctor output (looks like DEBUG=*). you didn't happen to try a dat --doctor test?

**Comment by mafintosh** [comment]
Just noting that it actually connects to the DHT fine based on the DEBUG output (no need to debug that) but it probably cannot hole punch any dat connections.

**Comment by karissa** [comment]
@mafintosh i'll see this guy tonight again i think and i'll try to get more output

**Comment by mafintosh** [comment]
@karissa if you could run [p2p-test](https://github.com/mafintosh/p2p-test) on his network that would be amazing (run it with karissa-test)

**Comment by baruchlab** [comment]
hello hello 
I ran p2p-test on the same network we were testing dat on on Wednesday... here are the results

Network tested. Thank you for participating.
{ time: '2016-09-23T16:15:19.557Z',
  description: '[karissa-test]',
  holePunchable: true,
  pings: 
   [ { port: 50571, host: '85.179.163.135' },
     { port: 50571, host: '85.179.163.135' } ] }
everything looks fine

**Comment by baruchlab** [comment]
I am sharing the directory now. ping me on patchwork for the link, see if you can get it. Baruch

**Comment by baruchlab** [comment]
hi Karissa I updated dat and am sharing now for the next 15 mins

**Comment by karissa** [comment]
@baruchlab what's the hash? :)

**Comment by baruchlab** [comment]
oops didn't see yr message.  6aab4cecd5f8a35ee29f8baa9b419579bed8e5b6e8b6a420f43fdf7d41be97d2
starting dat up again now

**Comment by joehand** [comment]
@baruchlab we weren't able to connect. Is this still the same network as before? And you upgraded the dat installation?

**Comment by baruchlab** [comment]
no I am in a train in Canada no with wifi completely different network.  I won't be back on the original network until the week of Oct. 18

**Comment by baruchlab** [comment]
results of p2p-test

{ time: '2016-10-06T21:15:46.349Z',
  description: 'karissa-test2',
  holePunchable: true,
  pings: 
   [ { port: 53646, host: '75.98.19.133' },
     { port: 53646, host: '75.98.19.133' } ] }

**Comment by baruchlab** [comment]
version is 11.4.0

**Comment by joehand** [comment]
okay, thanks. Someone was able to connect and get data (but @mafintosh and I weren't, so it may be our network here). We will be interested when you get back to the other network if it still works. Thanks!

**Comment by baruchlab** [comment]
do you want me to try again on other random networks, or only the first one I originally tried?

**Comment by joehand** [comment]
@baruchlab feel free to run p2p test on other networks, that will give us any data we need to help improve dat across networks.

**Comment by karissa** [comment]
I think this is fixed
