### ISSUE TITLE
File watch loop causes weird stats, emfile error

### ISSUE THREAD

**Issue by joehand** [datproject/dat#539]
Seems like a file watch loop is causing stats to increase a lot and eventually cause emfile errors.

This is on centos 7. 

![screenshot 2016-10-06 19 40 25](https://cloud.githubusercontent.com/assets/684965/19163672/c5eb007e-8bb1-11e6-814c-3ebf6c66e6a6.png)

**Comment by karissa** [comment]
is this fixed now? @mafintosh  @joehand

**Comment by karissa** [comment]
duplicate with #524
