### ISSUE TITLE
Incorrect byte counts in the progress bar

### ISSUE THREAD

**Issue by pfrazee** [datproject/dat#540]
When serving a dat, the progress bar is getting off from what the actual byte counts are, both in the "total" and "amount processed." This appears to only happen when I have Beaker running, and actively receiving (and processing) the new upload.

What happens is, even after the download is done, it keeps indicating that bytes are being upload (showing an upload rate). In Beaker, the download rate does the same. When it stops, it looks like this:

![screen shot 2016-10-09 at 5 53 52 pm](https://cloud.githubusercontent.com/assets/1270099/19224400/b7291760-8e4a-11e6-927a-d05714558b7b.png)
---

When the actual byte count is:

![screen shot 2016-10-09 at 5 54 55 pm](https://cloud.githubusercontent.com/assets/1270099/19224401/b72b91f2-8e4a-11e6-969b-3b9e4dee954e.png)

I can consistently reproduce by creating a new archive, hosting it on the cli with dat, opening it in beaker, and then adding live files. Pretty quickly, the count goes off.

**Comment by pfrazee** [comment]
It's worth noting, in Beaker, if I go through the list() entries and add up the reported .size of each, I get the same total number that Dat is giving. In the example above, that's 442.76MB. But! If I *deduplicate* any entries in list(), that does not happen.

Note: right now, hyperdrive's `list()` method actually gives the history of the metadata log. `list()` will be changed soon to reflect the current listing; until it is changed, Beaker will count entries multiple times if there ever overwritten. It seems likely, given the == numbers, that Dat is doing the same.

The interesting thing is, I'm only adding new files to the dat, not overwriting. So, there *shouldnt* be any double-counting. Perhaps this indicates that Dat is overwriting entries that have not been changed? Why don't I check on that now...

**Comment by pfrazee** [comment]
Oh man, I'm too good at this! My theory was correct. There are two issues at play:

 1. Because hyperdrive's `list()` is giving the history of the archive, Dat CLI is adding up the size of past versions of files. That leads to double-counting, triple-counting, etc.
 2. For some reason, Dat CLI is writing multiple identical entries for new files. Sometimes it doesnt happen, sometimes it happens twice in a row, sometimes it's many more times; but, in what I've seen, it's always multiple times in a row for the same file, and each entry is identical. Here's what it looks like in my debugger:

![screen shot 2016-10-09 at 6 13 21 pm](https://cloud.githubusercontent.com/assets/1270099/19224463/34139740-8e4c-11e6-8f9f-7388af18855a.png)

The first issue will be fixed when hyperdrive updates its `list()` implementation. The second issue is a bug somewhere in the dat cli's code, that we should fix to avoid unneeded bloat in the metdata feed.

**Comment by karissa** [comment]
Nice job p!

**Comment by juliangruber** [comment]
I make up for duplicate entries by `.list()` in hyperdrive-stats here: https://github.com/juliangruber/hyperdrive-stats/blob/master/index.js#L72-L81. I've created an issue for myself to integrate this here: https://github.com/datproject/dat/issues/541. So that should fix the dupe part.

The second issue is something that should be fixed, but won't mess with the stats necessarily, right?

**Comment by pfrazee** [comment]
> The second issue is something that should be fixed, but won't mess with the stats necessarily, right?

Yeah. I'll create a followup issue specifically about it. It's probably something like an event that's firing multiple times in the fs-watcher.

**Comment by juliangruber** [comment]
2) is fixed in https://github.com/juliangruber/hyperdrive-import-files/pull/21 :)

**Comment by joehand** [comment]
Removed byte counts! Fixed =)
