### ISSUE TITLE
Slow and high cpu usage when adding big files (>14GB)

### ISSUE THREAD

**Issue by G-Ray** [datproject/dat#545]
When I try to add 2 files of 7GB each, dat does not show any progress (see #544). However it eats around 70-80% of my CPU for more than 10 minutes until I see a completion of 21.6 GB/14.88 GB. Even after that, the process is not over as my cpu is still used.

Specs:
- Intel Atom N2840 @2.16GHz
- Archlinux

**Comment by pfrazee** [comment]
@mafintosh is it possible that his installation fell back to a js version of libsodium? Is there any way to quickly check which version is being used, js or native?

**Comment by karissa** [comment]
@G-Ray do you have any more info on this? I think this might be related to the memory leak that @mafintosh found. Could you update dat to the newest version and see if you could reproduce?

Also, using `--debug` at the end of the command will give us helpful output we can use! Thank you!

**Comment by karissa** [comment]
Closing this until we get more info
