### ISSUE TITLE
Question: does dat support branching and merging between different forks

### ISSUE THREAD

**Issue by white-gecko** [datproject/dat#551]
Does dat support branching and merging between different forks just as it is possible with git?

**Comment by joehand** [comment]
Hi @white-gecko, I think we answered this in IRC. But if you didn't get it:

> * mafintosh: dat is basically just p2p dropbox for files.
> *  mafintosh: we had branching forking and schemas in one of our earlier version but we're mostly just focusing on versioning+streaming of files now

**Comment by white-gecko** [comment]
thanks

**Comment by karissa** [comment]
forks and branches though could be done by simply copying the dat into a new one. We want to do that in the desktop app
