### ISSUE TITLE
dat should fail gracefully if another dat is already open on that dir

### ISSUE THREAD

**Issue by karissa** [datproject/dat#561]
1. Run a dat in one directory (`dat path/to/files`)
2. Open a new terminal
3. Run a dat on that same directory (`dat path/to/files`)

It tries to open the db but its already open. It should probably fail gracefully (give a nice message) or use level-party to just open it anyway even though there's another one up already

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: lock tweet-data/.dat/LOCK: Resource temporarily unavailable
    at /Users/karissa/node_modules/dat/node_modules/levelup/lib/levelup.js:119:34
    at /Users/karissa/node_modules/dat/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

**Comment by mafintosh** [comment]
It cannot use level-party. Single master is required.

**Comment by karissa** [comment]
cool lets try to fail gracefully

**Comment by mafintosh** [comment]
👍 this is a easy as listening for an error on the leveldb and printing an error message. pr welcome \o/

**Comment by juliangruber** [comment]
Part 1 of the fix is here: https://github.com/joehand/dat-js/pull/28
