### ISSUE TITLE
Ensure prebuilds for all dependencies

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat#581]
| module | [prebuild](https://github.com/mafintosh/prebuild) | [prebuild-ci](https://github.com/juliangruber/prebuild-ci) | windows |
| --- | --- | --- | --- |
| [utp-native](https://github.com/mafintosh/utp-native) | ✓ | ✓ | × (https://github.com/mafintosh/utp-native/issues/8) |
| [leveldown](https://github.com/Level/leveldown) | ✓ | ✓   | ✓ |
| [rabin](https://github.com/datproject/rabin) | ✓ | ✓ | ✓ |
| [fsevents](https://github.com/strongloop/fsevents)| ✓ (node-pre-gyp) | ✓ (custom script) | ✓ |
| [sodium-prebuilt](https://github.com/mafintosh/node-sodium-prebuilt) | ✓ | × (https://github.com/mafintosh/node-sodium-prebuilt/pull/5) | × (https://github.com/mafintosh/node-sodium-prebuilt/issues/2) |

**Comment by juliangruber** [comment]
fsevents uses node-pre-gyp instead of prebuild. I've seen it compiling though on my machine so I guess the infrastructure isn't set up fully.

**Comment by ShadowRZ** [comment]
@juliangruber Maybe I can build these for you.

**Comment by xoorath** [comment]
I've been looking into utp-native on windows. I made some notes here: [link](https://github.com/mafintosh/utp-native/issues/8)

**Comment by joehand** [comment]
All fixed! We do not use the sodium module anymore.
