### ISSUE TITLE
Deprecation warming

### ISSUE THREAD

**Issue by Fastidious** [datproject/dat#583]
I am getting:

```
Daedalus:Desktop david$ dat tst
(node:67574) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Sharing /Users/david/Desktop/tst
```

Known issue? Using `dat 11.6.0` under macOS.

**Comment by karissa** [comment]
What version of node are you using?

**Comment by Fastidious** [comment]
+karissa, I am using `v7.0.0`.

**Comment by maxogden** [comment]
I believe that deprecation warning got deprecated (lol). BTW we develop against Node LTS versions so v6 is recommended over v7 currently

**Comment by Fastidious** [comment]
@maxogden I don't understand about the deprecation being deprecated. On macOS I use brew to install node, and `v7.0.0` came down with a `brew update`, I believe. I didn't pick it. Everything else I have on node runs fine without complain, but dat.

**Comment by joehand** [comment]
@Fastidious this warning will be [removed soon](https://github.com/nodejs/node/pull/9529) (looks like 7.2.1). This was what Max meant when he said it will be deprecated. There is a [thread here](. This deprecation affected over 1000 modules but ) if you'd like further reading.

I'm going to close this as that warning will be removed in upcoming node v7 releases.
