### ISSUE TITLE
builds fail, ubuntu 16 LTS

### ISSUE THREAD

**Issue by alugarius** [datproject/dat#598]
![bildschirmfoto vom 2017-01-14 22-02-54](https://cloud.githubusercontent.com/assets/16763352/21958084/46532358-daa5-11e6-83af-a08530fee49a.png)

I don't know why someone develops in JavaScript,

i never done a successful build with it.  Not EVEN the package manager works, crap!

I go with IPFS   :(

**Comment by pfrazee** [comment]
This is actually a problem with your local machine's NPM config, unrelated to dat specifically.

Try this guide for solving it: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by alugarius** [comment]
i installed dat now.

how can i use it?

**Comment by joehand** [comment]
Hi @alugarius, what command did you use to install it? It looks like `dat` did not get installed globally (which allows you to run it as a command). To install it globally, use: 

```
npm install -g dat
```

If you have trouble installing it with that command, please see our [troubleshooting guide](https://github.com/datproject/dat#global-install) which will help fix the issue you posted.

**Comment by pfrazee** [comment]
I dont speak german, but it looks like it's instructing you to install liballegro4. I dont use ubuntu so I'm not sure why, but try running `sudo apt install liballegro4-dev` as it instructed

**Comment by joehand** [comment]
> I dont speak german, but it looks like it's instructing you to install liballegro4. I dont use ubuntu so I'm not sure why, but try running sudo apt install liballegro4-dev as it instructed

@pfrazee `liballegro4-dev` is another library that uses the `dat` [command](https://manned.org/dat) so linux thinks that is what isn't installed. But its an unrelated and unneeded package. 😞

**Comment by juliangruber** [comment]
Looks like your npm bin folder isn't inside `$PATH`. Run `npm bin --global` to find it and add it, then see if you still can't run dat.

@joehand yeah ubuntu doesn't find `dat` and advises to install the other software instead. You read that german correctly :)

**Comment by joehand** [comment]
Hi @alugarius, let us know if you still have trouble trying the suggestions above. We are still on improving our installation process but ubuntu should be covered for now (since we run our travis tests on linux).
