### ISSUE TITLE
.datignore

### ISSUE THREAD

**Issue by joehand** [datproject/dat#619]
_From @aaronshaf on January 21, 2017 17:23_

Like .gitignore, this would be a nice way to prevent certain files from being pushed/synced.

_Copied from original issue: joehand/dat-next#89_

**Comment by joehand** [comment]
_From @karissa on January 24, 2017 23:37_

this is a great feature request!

**Comment by pfrazee** [comment]
I just added this to bkr!

**Comment by joehand** [comment]
This is working but needs documentation.

**Comment by joehand** [comment]
Done!
