### ISSUE TITLE
'invalid algorithm' when using `dat publish` with SSL

### ISSUE THREAD

**Issue by joehand** [datproject/dat#620]
_From @karissa on January 26, 2017 22:42_

```
karissa ~/examples/tweet-data
$ dat publish --server=https://beta.datproject.org/api/v1
name: some-tweet-data
some-tweet-data
Publishing archive with name "some-tweet-data".
invalid algorithm
```

@mafintosh said it might be an SSL issue because we haven't seen this in the local tests.

_Copied from original issue: joehand/dat-next#107_

**Comment by karissa** [comment]
Fixed on the township side, needed to specify the algorithm ES512
