### ISSUE TITLE
File truncation issue

### ISSUE THREAD

**Issue by joehand** [datproject/dat#623]
_From @pfrazee on February 6, 2017 15:52_

Hey @mafintosh we've got a live one.

There's a file that's getting truncated in my dat inside of dathttpd. I'm using normal sharing on dat-next. It ends with some control characters I've never seen.

```
<li><a href="http^@^@
```

I think this is the issue you and I discovered with the verify-on-read addition, where a dat process will ask for old content chunks once it discovers theyre missing due to verify-on-read, and then overwrite the current version with old data. You said you had a fix planned for this, IIRC. What's the status on that?

_Copied from original issue: joehand/dat-next#117_

**Comment by joehand** [comment]
_From @pfrazee on February 6, 2017 17:13_

Max suggested it may be related to https://github.com/datproject/dat-node/issues/79 and this fix https://github.com/datproject/dat-node/commit/9af49c8ca1bb8788815fdf11c5a8a870fa56659d, but I was using dat-next latest as of yesterday, which should include those fixes.

**Comment by joehand** [comment]
This should be fixed in `12.0.1` on the CLI side.

**Comment by pfrazee** [comment]
Great. I'll comment if I have any other problems. (I can't close or reopen since this is a copy of my original issue)
