### ISSUE TITLE
Clone/Pull triggers a file watch event on source

### ISSUE THREAD

**Issue by joehand** [datproject/dat#628]
Share a NEW Dat on one terminal:

```
mkdir share-dir
echo "hello" > share-dir/hola.txt
DEBUG=dat,dat-node dat share ./share-dir
```

Clone the new Dat on another one:

```
dat clone <link> down-dir
```

You'll see the files watch trigger when then clone connects:

```
  dat Imported /Users/joe/Desktop/share-dir/hola.txt +24ms
  dat Import finished +0ms
  dat Network: first peer connected +10s
  dat File watch updated: hola.txt +0ms
  dat Imported /Users/joe/Desktop/share-dir/hola.txt +2ms
  dat File updated: hola.txt +0ms
```

So it seems like a remote download is affecting the source file. May be related to #626 and #623. 

PR #627 fixes this by not importing the files again, but still is an issue.

**Comment by joehand** [comment]
Looks like the PR doesn't totally fix it. I was able to get it to happen again by adding a third connection.

**Comment by joehand** [comment]
Fixed by not downloading content as source.

**Comment by karissa** [comment]
woot!
