### ISSUE TITLE
error in File count

### ISSUE THREAD

**Issue by sdockray** [datproject/dat#633]
Testing today with 12.0.1

> % DEBUG=dat,dat-node dat share
> 
>   dat Reading archive in dir /path/to/Directory Name +0ms
>   dat-node Running initArchive on /path/to/Directory Name with opts: { _: [],
>   utp: true,
>   quiet: false,
>   import: true,
>   ignoreHidden: true,
>   'ignore-hidden': true,
>   watch: true,
>   dir: '/path/to/Directory Name',
>   logspeed: 200,
>   port: 3282,
>   debug: 'dat,dat-node',
>   server: 'https://datproject.org/api/v1',
>   exit: false } +4ms
>   dat-node Making/Reading archive database +5ms
>   dat-node Reading existing keys in drive +8ms
>   dat-node Drive has 0 existing keys. +8ms
>   dat-node No existing feeds in drive, creating new archive. +0ms
>   dat-node Archive initialized +3ms
>   dat-node Archive key 84c28e88181a19dd012d791a308f03106a7a53f5889e0c2d22e7a1952a720822 +0ms
>   dat-node Opening archive 84c28e88181a19dd012d791a308f03106a7a53f5889e0c2d22e7a1952a720822 +1ms
>   dat-node Archive opened +22ms
>   dat-node initArchive callback +0ms
>   dat Share: sync on 84c28e88181a19dd012d791a308f03106a7a53f5889e0c2d22e7a1952a720822 +1ms
>   dat Importing updated & new files into archive +15ms
>   dat-node Importer created. Counting Files. +6ms
>   dat-node File count finished { files: 6, dirs: 3, bytes: NaN } +191ms
> /home/s/.npm-packages/lib/node_modules/dat/node_modules/pretty-bytes/index.js:6
>                 throw new TypeError(`Expected a finite number, got ${typeof num}: ${num}`);
>                 ^
> 
> TypeError: Expected a finite number, got number: NaN
>     at module.exports.num (/home/s/.npm-packages/lib/node_modules/dat/node_modules/pretty-bytes/index.js:6:9)
>     at null._repeat (/home/s/.npm-packages/lib/node_modules/dat/lib/share.js:131:92)
>     at wrapper [as _onTimeout] (timers.js:270:19)
>     at Timer.listOnTimeout (timers.js:89:15)

and the directory contents are:

> % tree
> .
> ├── An Escape Act
> │   ├── An Escape Act.pdf
> │   └── cover.jpg
> ├── Kingdom of the Dolls
> │   ├── cover.jpg
> │   └── Kingdom of the Dolls.pdf
> └── Social Studies A Conversation about Art and Social Engagement
>     ├── cover.jpg
>     └── Social Studies A Conversation about Art and Social Engagement.pdf

**Comment by joehand** [comment]
Thank you for the bug report! That is very strange. 👻 

Is there anything unusual about that directory (e.g. they are symlinks, the files are empty, or other magic)?

This should be fixed in https://github.com/joehand/count-files. I will add a CLI tool there to count a given directory so we can start debugging this.

**Comment by joehand** [comment]
Ah! I got a `NaN` for the bytes first run with the count-files CLI.

**Comment by sdockray** [comment]
No symlinks, no empty files.  Could ownership be a problem?

> -rwxrwxr-x 1 user  www-data 925703 Feb  8 05:45 An Escape Act.pdf
> -rw-rw-rw- 1 uwsgi uwsgi     30002 Feb  8 05:45 cover.jpg

One other note is that when I run without debug it behaves as though its working:

> % dat sync
> Syncing Dat Archive: /lockers/hmmmmm/processed/Directory Name
> Link: dat://db368d73549159ef13070ff093430c80e8c7016bcbdd0e97daa5a84da1827cdb
> 
> Watching for file changes...
> Total Size: 6 files (2.73 MB)
> 
> Looking for connections in Dat Network...

but with debugging it gives (this time not the error, but still NaN):

> % DEBUG=dat,dat-node dat sync
>   dat Reading archive in dir /path/to/Directory Name +0ms
>   dat-node Running initArchive on /path/to/Directory Name with opts: { _: [],
>   utp: true,
>   quiet: false,
>   import: true,
>   ignoreHidden: true,
>   'ignore-hidden': true,
>   watch: true,
>   dir: '/path/to/Directory Name',
>   logspeed: 200,
>   port: 3282,
>   debug: 'dat,dat-node',
>   server: 'https://datproject.org/api/v1',
>   createIfMissing: false,
>   exit: false } +4ms
>   dat-node Making/Reading archive database +7ms
>   dat-node Reading existing keys in drive +7ms
>   dat-node Drive has 2 existing keys. +10ms
>   dat-node keys: [ '04994c0e76bbda31c81fb02d4e664e2ad701262cc1e65b6b103443081222ac91',
>   'db368d73549159ef13070ff093430c80e8c7016bcbdd0e97daa5a84da1827cdb' ] +0ms
>   dat-node Making archive with key db368d73549159ef13070ff093430c80e8c7016bcbdd0e97daa5a84da1827cdb +1ms
>   dat-node Archive initialized +21ms
>   dat-node Archive key db368d73549159ef13070ff093430c80e8c7016bcbdd0e97daa5a84da1827cdb +0ms
>   dat-node Opening archive db368d73549159ef13070ff093430c80e8c7016bcbdd0e97daa5a84da1827cdb +0ms
>   dat-node Archive opened +1ms
>   dat-node initArchive callback +0ms
>   dat Archive owner, syncing local updates to network +0ms
>   dat Share: sync on db368d73549159ef13070ff093430c80e8c7016bcbdd0e97daa5a84da1827cdb +1ms
>   dat Importing updated & new files into archive +15ms
>   dat-node Importer created. Counting Files. +6ms
>   dat-node File count finished { files: 6, dirs: 3, bytes: NaN } +138ms
>   dat Import finished +22ms

**Comment by sdockray** [comment]
I don't know if there's something fishy with how I'm debugging?

on a clean directory:
DEBUG=dat,dat-node dat share **gives the TypeError**
DEBUG=dat,dat-node dat sync **also gives the TypeError**
dat sync **appears to work**
DEBUG=dat,dat-node dat sync **no TypeError, but `bytes: NaN`**

**Comment by joehand** [comment]
@sdockray its definitely me. I found the bug, it was quite silly, sorry!

If you reinstall dat (or just update `node_modules/count-files` to version 2.1.2) it should be fixed. I'm also publishing a cli counter we can use to double check in a minute.

**Comment by sdockray** [comment]
Great it's working!

**Comment by joehand** [comment]
Sweet!  Thanks for reporting the issue.

You can also now try the directory counter directly:

```
npm install -g count-files
cd my-dir-to-count
count-files
```

You should get not `NaN` 😄 .

**Comment by sdockray** [comment]
Yay!
Prior to this bug I wasn't able to successfully clone (well it would fetch metadata but then hang at 0% on contents) and now I can.
