### ISSUE TITLE
blocksprogress can exceed blockstotal

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat#638]
As per https://github.com/datproject/dat/blob/master/lib/download.js#L114-L115 - chances is this might be fixed in SLEEP b/c we get a better grip on bytes progress and no longer need to rely on `hyperdrive-stats`, but still worth opening an issue for I reckon (:

**Comment by joehand** [comment]
👍  also likely related to our replication issues, #635. 

The bug results from clients that have full history vs clients that only want latest and how to reconcile those.

**Comment by joehand** [comment]
Not relevant in new hyperdrive, closing.
