### ISSUE TITLE
cookbook item for 'using dat with git to distribute large files'

### ISSUE THREAD

**Issue by okdistribute** [datproject/dat#641]
A simple tutorial and example project on the docs.datproject.org cookbook section that shows how one can use github to distribute small files along with dat to distribute large files.

**Comment by joehand** [comment]
Now that we support dat.json url, we can get going on this! It'd be great to have a *replace git lfs* tutorial. 

Some example papers + code we could draw from or PR (todo: find more using git lfs):

* https://github.com/cpbl/osm-completeness (uses wget)
* ... more

**Comment by joehand** [comment]
This is what I think we need for the complete workflow:

### Replace git lfs storage

**Goal:** Publish data to datproject.org/jhand/my-dat and easily clone from inside a git repo. 

* dat create (in git repo)
* commit dat.json to git
* dat publish (we'll rehost data for researchers that want to try it)
* git push
* dat push (push to our host)

Right now we are missing:

* dat push
* Automatic rehosting for specific users in registry

**Comment by okdistribute** [comment]
done
