### ISSUE TITLE
do not print out key in debug

### ISSUE THREAD

**Issue by joehand** [datproject/dat#643]
Privacy concern.

Check this in dat-node too.

**Comment by joehand** [comment]
Started branch `remove-key-printout` that removes printing all keys (debug or not). It also adds a key command, `dat key`, to get the key. Unfortunately, this makes the `dat share` command mostly useless because you can't get the key unless you stop sharing.

Open to suggestions here. The less drastic thing to do for now is just remove key from debug statements.

**Comment by juliangruber** [comment]
If we are to introduce `dat key` for this, would you then need to `dat create && dat share && dat key`?

**Comment by karissa** [comment]
Dat key seems to be the thing that will show the key when it's not running.

@juliangruber 'dat share' works for create and sync

**Comment by joehand** [comment]
> Dat key seems to be the thing that will show the key when it's not running.

Yep! Also as currently implemented, `dat create` will still print out the key. It may be okay to show the key on `dat create`, `dat share`, and `dat sync` for owners.

We were more concerned with printing out the key for downloading users, we do not want them to share a key accidentally if they didn't create the dat to start with.

**Comment by joehand** [comment]
Done in v13.1

* shows the key for sharing commands 
* Adds `--show-key` option to show key for download commands.
* Adds `dat status` to print out key.
* Does not in show key ever DEBUG mode.
