### ISSUE TITLE
Populate .gitignore on create

### ISSUE THREAD

**Issue by joehand** [datproject/dat#652]
_From @pfrazee on November 18, 2016 15:15_

Since it can be disastrous to commit the .dat folder, I suggest we create a .gitignore file if it DNE, and append .dat to it.

_Copied from original issue: joehand/dat-next#4_

**Comment by joehand** [comment]
Yes. Ideally we'd do store them elsewhere, #41. 

If that isn't landed by the time we release this as the main CLI, we'll implement this.

**Comment by rnkn** [comment]
Or append to `.git/info/exclude`

**Comment by joehand** [comment]
Secret keys are stored outside of the shared directory, so this is no longer needed. Committing the .dat folder is 👌 .
