### ISSUE TITLE
[cmd] FORK - copy another archive and reset metadata

### ISSUE THREAD

**Issue by joehand** [datproject/dat#653]
_From @pfrazee on November 18, 2016 15:14_

It'd be neat to have a fork command that's similar to what's in beaker.

Download the current files, then create a new dat and populate it with them.

_Copied from original issue: joehand/dat-next#3_

**Comment by joehand** [comment]
This would be nice. My only hesitation is that it may imply that we have a merge/PR workflow, similar to git. 

Since it is pretty easy to do by hand, we may want to wait on this one:

```
dat-verb clone <link> my_data
cd my_data
rm -rf .dat
dat-verb create
```

**Comment by joehand** [comment]
_From @pfrazee on November 19, 2016 19:3_

Totally cool with not doing this now, but I dont think it suggests merging.
Branching would, but forking is about making a fresh copy.

**Comment by joehand** [comment]
_From @karissa on December 8, 2016 20:3_

+1 on forking now. Say "merge not implemented pr's welcome!"

**Comment by okdistribute** [comment]
This will be possible in the next version of [Beaker Browser](https://beakerbrowser.com) @pfrazee
