### ISSUE TITLE
What encryption scheme does this use?

### ISSUE THREAD

**Issue by ethanwillis** [datproject/dat#662]
I see it says public-private key in several places, but what is the actual encryption scheme used at the data level and at the transport level?

**Comment by joehand** [comment]
Hi @ethanwillis! We should get that in our docs, we still have them spread out a few places.

* Dat keys are generated using the [ed25519](https://ed25519.cr.yp.to/) scheme.
* We use a *discovery key* to look for peers over the network, which is a SHA256 of the public key.
* All messages, encoded using Protocol Buffers, are encrypted using the public key with a random 24 byte nonce using [sodium encryption](https://github.com/mafintosh/sodium-encryption)

We have a bit more details on the [datprotocol.com](https://www.datprotocol.com/) site and our [draft paper](https://github.com/datproject/docs/blob/master/papers/dat-paper.pdf). 

Let me know if you have more questions here! I can also point you to the modules where all these things happen, if you'd like. Thanks.
