### ISSUE TITLE
Warn when CLI is installing in unsupported node

### ISSUE THREAD

**Issue by maxogden** [datproject/dat#669]
A user reported they couldn't install dat CLI without having all of XCode installed. Underlying issue was they were on 0.10 but the npm output wasn't helpful. I'm not sure how, but if there's a way to print a clear warning that they need to upgrade their node that might be nice.

**Comment by joehand** [comment]
Added in 13.1.0:

```
❯ dat
Node Version: v0.12.18
Unfortunately, we only support Node >= v4. Please upgrade to use Dat.
You can find the latest version at https://nodejs.org/
```

Dat will now fail if node is <4. We are using template strings in CLI output, so we cannot support earlier version at all anymore.
