### ISSUE TITLE
can't install DAT on Windows

### ISSUE THREAD

**Issue by protw** [datproject/dat#677]
OS: Windows 10 64bit

I've got preliminary installed:

- node v.6.9.4
- npm v.4.3.0
- node-gyp -v.3.5.0
- python v.3.6.0 (env variables PATH and PYTHON are set to an appropriate directory)

Then I run CMD in **admin mode** and put the following command `npm install -g dat`.

Eventually the installation scenario displays in two places the following stack of messages:
```
C:\Users\Admin\AppData\Roaming\npm\node_modules\dat\node_modules\utp-native>if not defined npm_config_node_gyp (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Admin\AppData\Local\Programs\Python\Python36", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Admin\AppData\Roaming\npm\node_modules\dat\node_modules\utp-native
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

What's wrong?

**Comment by joehand** [comment]
> What's wrong?

Hello! Sorry about your trouble. We still don't quite fully support Windows. We have some native modules that need to be compiled. You should be able to compile them but it looks like node-gyp can't execute python.

Check out the installation guide on [node-gyp](https://github.com/nodejs/node-gyp#installation) - you may need to make sure to set the python path using those methods.

We are working on prebuilding those modules, #581 which will allow easier installation on windows (without the python requirement).

Thanks for letting us know, we'll try to get this working soon.

**Comment by mafintosh** [comment]
utp is actually an optional dependency right now so dat should still work even though npm prints out that error message (npm's ux isn't great around optional deps)

**Comment by ShadowRZ** [comment]
But why utp can't build on Windows?

**Comment by joehand** [comment]
> But why utp can't build on Windows?

It can build on Windows with the correct dependencies. I think you need python and Visual C++ Build Tools. See the installation guide of node-gyp linked above for more details.

**Comment by ShadowRZ** [comment]
I'll try.

于 2017年3月18日 GMT+08:00上午4:24:49, Joe Hand <notifications@github.com> 写到:
>> But why utp can't build on Windows?
>
>It can build on Windows with the correct dependencies. I think you need
>python and Visual C++ Build Tools. See the installation guide of
>node-gyp linked above for more details.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/datproject/dat/issues/677#issuecomment-287461881

-- 
From K-9 Mail

**Comment by ShadowRZ** [comment]
@joehand No, I tested.

**Comment by joehand** [comment]
> @joehand No, I tested.

What was the error you received?

**Comment by ShadowRZ** [comment]
Bareword.
Marco I64u not replaced correctly.

于 2017年3月19日 GMT+0800AM12时56分17秒, Joe Hand <notifications@github.com> 写到:
>> @joehand No, I tested.
>
>What was the error you received? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/datproject/dat/issues/677#issuecomment-287559091

-- 
使用 K-9 Mail 发送自我的手机的说～
来自NicoNicoNi的HID_System的说～

**Comment by ShadowRZ** [comment]
What about a Windows installer?

**Comment by karissa** [comment]
Have you tried wth Python 2 installed? You can use virtualenv or anaconda to change your Python version in windows.

**Comment by ShadowRZ** [comment]
I'll start a fresh VM to test this.
It takes a long time since this VM is deleted shortly.

**Comment by joehand** [comment]
This should be fixed with a new installation, UTP now works on windows!
