### ISSUE TITLE
expected behaviour deleted files

### ISSUE THREAD

**Issue by viehwegerlib** [datproject/dat#694]
hi,

i run the latest npm dat version:

```
npm uninstall -g dat
npm install -g dat
```

```
mkdir send
echo 'hi' > send/foo.bar
dat share send/

# another screen
mkdir receive
dat clone key receive/
cat receive/foo.bar # hi
```

but now i delete `send/foo.bar` and `dat pull receive/`, but the receive directory still contains the file with "hi". 

now i do `echo 'hi hi hi' > send/foo.bar` and pull the changes from the receive folder, and foo.bar now contains 'hi hi hi'.

is this the expected behaviour?

i guess what i am asking is:

- how does dat deal with deleted files?
- how does dat deal replaced files? like, can i `cp foo.bar send/foo.bar`? currently, the replaced file in send/ changes, while receive/ does not after pull.

thanks a lot!

**Comment by joehand** [comment]
> how does dat deal with deleted files?

It doesn't 😄 . The current version does not do anything about deleted files on either end.

> how does dat deal replaced files? like, can i cp foo.bar send/foo.bar? currently, the replaced file in send/ changes, while receive/ does not after pull.

Right now once a file is added there is no way to remove that metadata entry. So you could add it in another place `send/foo.bar` but it'd still be in the original location too.

However, we should be supporting the full range of file system actions better in the next few weeks.

**Comment by viehwegerlib** [comment]
ah, that explains a lot. my use case is the following: i put a database dump in a dat shared directory, then changes to the database are made. ideally, i would like to dump the updated database json in the same dat folder, so that people pulling it can then import tge database changes. 

how would you recommend to do that with dat without creating many different database dumps? 

thanks a lot!

**Comment by joehand** [comment]
> how would you recommend to do that with dat without creating many different database dumps?

Updating the same file repeatedly will work fine. You can dump to `db-dump.json` regularly and all the clients will automatically download the latest file. 

Right now the CLI does not store the history of this file, so it'll be impossible to roll back db dumps. But it'll be easier to store the full history or selectively sync specific files in the future.

Your Zoo projects looks cool! Excited to see where that goes.

**Comment by viehwegerlib** [comment]
I tried dumping to the same file and dat works like a charm, thanks, that was easy :) I am looking forward to those dat changes in the future. 

And zoo wouldn't be nearly as convenient without dat, so a huge thanks for all the effort you guys put into such a tremendeously useful project.
