### ISSUE TITLE
Can not download file from clone commod

### ISSUE THREAD

**Issue by zw231212** [datproject/dat#698]
I shared files with this：
![image](https://cloud.githubusercontent.com/assets/12821929/24540215/bfc010f6-1624-11e7-8d07-328b088e8b6a.png)

But when I clone the file ,I got this:

![image](https://cloud.githubusercontent.com/assets/12821929/24540225/cd81ad6c-1624-11e7-8eb0-e798fd9c3f5c.png)

node version:v6.10.1
npm version:3.10.10
dat version:12.0.3

Which step I did wrong ?

**Comment by joehand** [comment]
Hi @zw231212! this looks like you did it correctly but the two dats could not connect to each other. There could be a few things that caused that. A few clarifications or things to try:

* Were both commands were running at the same time?
* It looks like there were run on the same machine. Was your wifi turned on & connected to a network? Dat uses MDNS to discover peers on the local network (including the same computer).
* Can you run the dat doctor? Run `dat doctor` and `dat doctor <key>`. (it'll give you a key when you run it the first time) in the two places you were trying to share and download the dat.

**Comment by joehand** [comment]
Hello @zw231212, we've released a very new version of dat, version 13. Please upgrade and let us know if you still have issues. 

If you still see this issue, please address some of the questions above to help us debug. Thanks!
