### ISSUE TITLE
Running Dat on the server

### ISSUE THREAD

**Issue by Fastidious** [datproject/dat#738]
Could someone who knows expand on [Dat's server setup](https://docs.datproject.org/server)? How one tells Dat which server to use to mirror and store the data? Will (can) such server be also used as "seeder" or gateway?

On the `TL;DR`, there is a hash, `ff34725120b2f3c5bd5028e4f61d14a45a22af48a7b12126d5d588becde88a93`, what is that? Is it just an example, or a "magical" one?

**Comment by maxogden** [comment]
Hey there, the hash is the key that dat clients use to look up remote data sources, which serves a similar purpose as an IP address. With dat links, anyone with a copy of the data can announce it, and others who are downloading can discover them as data sources. So it works in a 'many to many' fashion rather than a 1-to-1 fashion.

The server docs you linked to just show how to run a process in the background that will keep sharing a dat on a server, which means that clients downloading that key will always find the server when they go to discover data sources. The link in the docs is just an example key, all dat keys are unique.

**Comment by Fastidious** [comment]
@maxogden thank you for the explanation. Assuming I have a process in the background running a dat, how will I point a client to use my server? Is there a way I can force/configure the data sources discovery on the client, to be always a specific server?

Now, assuming I do not need to seed or stash data on a server, there will still be the need to have a discovery server. Do you know how to run how of those? Are there instructions somewhere? Of course, I will still need to know how to configure a client to use that specific server for data transfer.

I would appreciate very much if you could lead me to a site with the documentation I need to accomplish the above.

**Comment by joehand** [comment]
Hi @Fastidious, we don't have all the docs for that in a single place right now. I'm not quite following what you are trying to do beyond connect a client to a server hosting a Dat, which should be straightforward with the existing CLI tools running on both the client and server.

I'll try to give you some pointers on your questions, and hopefully that will help clear your use case up:

> Assuming I have a process in the background running a dat, how will I point a client to use my server? Is there a way I can force/configure the data sources discovery on the client, to be always a specific server?

They'll automatically connect if they are running on the same key. But if you want your client to *only* connect to your server, you can whitelist the IP address in [discovery-swarm](https://github.com/mafintosh/discovery-swarm).

> there will still be the need to have a discovery server. Do you know how to run how of those? Are there instructions somewhere?

We run [discovery servers](https://github.com/joehand/dat-swarm-defaults) that all our tools use by default. You can also run your own [dns discovery](https://github.com/mafintosh/dns-discovery) server and [dht server](https://github.com/webtorrent/bittorrent-dht) if you only want your clients in the network. If you run your own discovery network, then those clients won't be able to discovery any keys outside of that network (and visa-versa).

Unfortunately, most of these options are not yet available in the CLI so you'll have to create your own tools. There is a bit more on the server config mentioned above [on this page](https://www.datprotocol.com/guides/hosting-dats-from-a-server.html). We also have [an open issue](https://github.com/datproject/docs/issues/50) on security that goes over some of these issues.

**Comment by joehand** [comment]
@Fastidious let us know if you have any other questions, closing for now.
