### ISSUE TITLE
importing - ignore mtime on root dir

### ISSUE THREAD

**Issue by joehand** [datproject/dat#741]
We dont need to be updating mtime on the root dir, should just ignore it. 

In this case, I updated an ignored file but the root dir mtime changed, so it got imported again:

<img width="439" alt="screen shot 2017-05-09 at 8 18 38 pm" src="https://cloud.githubusercontent.com/assets/684965/25881951/bf656220-34f4-11e7-8d6a-c0066859c48e.png">

**Comment by mafintosh** [comment]
It is actually safe to ignore all directories if you want. Hyperdrive still works. I was doing this in next-next

**Comment by joehand** [comment]
Updated in dat-node `v3.3.0`
