### ISSUE TITLE
tell user if dat version is out of date

### ISSUE THREAD

**Issue by joehand** [datproject/dat#777]
I like how yarn does this:

<img width="617" alt="screen shot 2017-05-22 at 10 04 18" src="https://cloud.githubusercontent.com/assets/684965/26319992/15821cda-3ed6-11e7-9b79-882b47e63096.png">

**Comment by juliangruber** [comment]
Thinking about implementation, what about we run the version check in a disconnected child process which then writes the most current version to `~/.dat-version.txt`. The next time you run a dat command, it will read that and warn you, but you never have to wait for anything.

**Comment by mafintosh** [comment]
Alternative, print out dat version on every command.
