### ISSUE TITLE
bike shed notes

### ISSUE THREAD

**Issue by joehand** [datproject/dat#780]
Random things that came up with max:

* Change import language to "creating metadata"
* add `dat create -y`
* make two commands: 1) create .dat and dat.json 2) import and share to network
* Cleanup whitespace on dat create
* dat link from chalk (on create) wasn't blue, maybe b/c of template literal?
* `dat keep` - > `dat backup` ?

**Comment by karissa** [comment]
yeah `dat backup` sounds good

**Comment by joehand** [comment]
These should be mostly addressed. I'll leave a note in the `dat keep` pr about changing to backup.
