### ISSUE TITLE
Publish should upload the dat metadata to the registry

### ISSUE THREAD

**Issue by karissa** [datproject/dat#803]
So even if the content isn't available, we are caching the metadata contents when people publish. Otherwise, if people publish but forget to share, it just displays an empty 'loading' screen.

**Comment by joehand** [comment]
Is there some way to do that over the registry API? 

I can't remember if publishing automatically adds it to hypercore-archiver, but seems like something like that would be the way to do it. Then we have to figure out how to monitor progress on the remote.

**Comment by karissa** [comment]
Yeah, I think maybe there could be a response from publish that contains a variety of error and success codes which the client could parse. One of those could be 'dat not found'. So the publish process would simply have to make sure the dat is hosting over the network.

Also if we're going to refactor the publishing part we could also implement paul's scheme for publishing: https://github.com/datprotocol/hypercloud/blob/master/docs/flows/dat-ownership-proof.md
