### ISSUE TITLE
Navigating the http server of a running dat results in broken url

### ISSUE THREAD

**Issue by beingalink** [datproject/dat#808]
See [here](https://www.dropbox.com/s/cg9zyg3gze47lyf/Screenshot%202017-06-16%2014.02.55.png?dl=0).

**Comment by joehand** [comment]
I don't really understand what is going on here. Can you give some more details on how to reproduce? 

Can upload images directly to github, it makes it a bit easier and better for posterity. You can upload by dragging them into issue box or selecting at the bottom, thanks.

<img width="755" alt="screenshot 2017-06-16 14 02 55" src="https://user-images.githubusercontent.com/684965/27239456-e836d252-5285-11e7-8fde-e89598825bd2.png">

**Comment by beingalink** [comment]
It might be a problem related to firefox nightly. I couldn't reproduce it in Safari yet. Closing for now. Will re-open when I find a reliable way to reproduce it cross-browser.
