### ISSUE TITLE
Can't connect p2p (windows)

### ISSUE THREAD

**Issue by marxo** [datproject/dat#809]
When I try to connect to a remote peer I get:

```
Dat could not find any connections for that link.
There may not be any sources online.
```

`dat doctor` is returning only `Trying to connect to xx.xx.xx.xx`

Tried Windows 10 and Ubuntu subsystem for Windows.

Any ideas?

**Comment by karissa** [comment]
I think this might be because utp is not supported on windows, is that right?

**Comment by marxo** [comment]
@karissa I can confirm that maybe with this:

```
[info] Testing connection to public peer
[error] FAIL - unable to load utp-native, utp connections will not work
[info] TCP ONLY - success!
```

**Comment by joehand** [comment]
> Does that effectively mean we can't signal in p2p mode?

Maybe, we use UTP to get around firewalls or otherwise inaccessible networks. If you are able to open a port for dat you should be able to connect p2p easier. By default, dat uses `3282` port but you can pass other ports to any command: `dat share --port 61123`.

**Comment by pfrazee** [comment]
Realistically speaking, I doubt that TCP will connect to anything except
for peers that are running on servers

**Comment by joehand** [comment]
UTP is now supported on windows! Please reinstall to update the dependencies.
