### ISSUE TITLE
Will there be python API ？

### ISSUE THREAD

**Issue by zarchary** [datproject/dat#814]

**Comment by yoshuawuyts** [comment]
The Dat team might create a C or Rust version that can have bindings to
Python (and R). There's no concrete roadmap for this at the moment though;
the main focus so far has been on iterating on the JavaScript version.

We've talked about releasing a protocol implementation guide so other
languages can implement native versions, but beyond releasing the Dat
whitepaper I don't believe there's been done any further work on that.

Hope this somewhat answers your question, cheers!

**Comment by karissa** [comment]
I think a Python API is possible with a wrapper over dat http!

**Comment by joehand** [comment]
I'd be great to have a daemon for this with a HTTP interface. We can take a lot of the work put into the desktop app managing multiple dats and use that.

**Comment by DonaldTsang** [comment]
@yoshuawuyts @joehand please make a Python API for use in https://github.com/hydrusnetwork/hydrus

**Comment by yoshuawuyts** [comment]
@DonaldTsang The main bottleneck for a native python API to happen would be funding. I estimate getting a native Dat implementation working in Python would require around 2 people years worth of work.

But as @karissa suggested, building an HTTP client around https://github.com/datproject/hyperdrive-http might provide a feasible path forward in the near term. It might be less ideal than a full native impl, but it would probably work well for a server application like Hydrus.

**Comment by DonaldTsang** [comment]
@yoshuawuyts best to be able to package the whole of DatProject into a single binary so that we can use it easier (for Python-only devs).

**Comment by millette** [comment]
@DonaldTsang binaries: https://github.com/datproject/dat/releases/tag/v13.11.4
