### ISSUE TITLE
neat-log is quiet by default if DEBUG env var is set

### ISSUE THREAD

**Issue by ralphtheninja** [datproject/dat#830]
~~Also when the clone finished and I do `dat . --http` inside the dat folder, it's also silent.~~

EDIT:

This happens on all output made my `neat-log` since if I have `DEBUG` env var set to something, then `--quiet` will default to `true`.

![dat](https://user-images.githubusercontent.com/308049/28502206-9ae8f6d0-6fed-11e7-88b3-482d7879df54.png)

**Comment by ralphtheninja** [comment]
Ps. Using node `8.2.0` on linux 64 bits.

**Comment by ralphtheninja** [comment]
@joehand What is the purpose of the `!!process.env.DEBUG` thing in `cli.js`? I'm thinking you might be using this when debugging dat for some reason, but it was super confusing to me today when I got no output from dat all of a sudden :)

**Comment by ralphtheninja** [comment]
Also a bit counterintuitive to me, since if I do have `DEBUG` set to something, you might expect it to give more output instead of nothing.

**Comment by joehand** [comment]
@ralphtheninja ah ya that may not be well thought out. 

The use is for when we set debug on for dat:

```
DEBUG=dat* dat sync
```

which will print out all the debug statements but none of the regular output. neat-log swallows up output pretty greedily so that is why we have it quiet if `DEBUG` is true. 

We need to output *something* when `DEBUG = true && DEBUG != dat`.

**Comment by mafintosh** [comment]
Perhaps a simple message telling the user that it is enabling quiet mode
cause the DEBUG env is set would be enough

**Comment by ralphtheninja** [comment]
It seems to me that checking `var isDebug = debug.enabled` should be enough (it's set to true if DEBUG=dat or DEBUG=dat*).
