### ISSUE TITLE
If peer send 404, change to another peer

### ISSUE THREAD

**Issue by Plasmmer** [datproject/dat#835]
Also, punish peers that are most downvoted for sending 404 errors.
Please don't repeat the mistake of ZeroNet.

**Comment by joehand** [comment]
Is this a problem you've seen in Dat?

In Dat, swarms are limited to each Dat link. You do not try to connect to a peer unless they have *some* of the data you're looking for. We don't have a rating system for peers right now but no one has raised this issue because of how Dat is designed.

**Comment by joehand** [comment]
Let us know if this is an issue you've experienced, closing otherwise.
