### ISSUE TITLE
Plans to support IPFS?

### ISSUE THREAD

**Issue by Plasmmer** [datproject/dat#837]

**Comment by pfrazee** [comment]
Dat and IPFS handle the same tasks. Similar to how FTP and SCP are similar at their cores (connection-based file transfer protocols). It'd make more sense to consider IPFS support in Beaker, and we discuss that here: https://github.com/beakerbrowser/beaker/issues/480

**Comment by joehand** [comment]
Its possible you could build an IPFS storage provider to use inside of Dat (not quite sure though, I am not 100% familiar with how IPFS storage works). However, as pfrazee said, they are different protocols and we do not plan to implement another protocol in the Dat CLI. See more here: https://docs.datproject.org/faq#dat-vs
