### ISSUE TITLE
dat CLI executable

### ISSUE THREAD

**Issue by joehand** [datproject/dat#842]
Allow users to use Dat without installing Dat/npm.

`pkg`, https://github.com/zeit/pkg/, is now working for Dat and the native modules. The main thing we have to figure out is how to effectively [package everything up](https://github.com/zeit/pkg/#native-addons) and distribute it, ideally via Travis.

We could probably reuse some of the work done for the desktop here.

(thanks to @millette for the reminder on this, https://github.com/datproject/projects/issues/17)

**Comment by e-e-e** [comment]
This could be achieved by writing a small package script, which runs the pkg command and then, using github api, push the builds to releases.
I am not sure if something already exists for simply pushing artifacts to github, but electron-builder's [gitHubPublisher.ts](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-publish/src/gitHubPublisher.ts) could potentially be modified to suit this purpose.

**Comment by joehand** [comment]
Almost there! #849 

* Using pkg to build
* Travis deploys to github releases automatically

I had trouble with native modules on the downloaded release, so still have to look into that.

**Comment by joehand** [comment]
Also, we should probably make it so travis only builds on tagged versions, not all master commits. (reminder)

**Comment by aschrijver** [comment]
@joehand When I try `npm package install` on a clean project I still get a lot of warnings: https://gist.github.com/aschrijver/def029ad7ac6581d8e7530f27c877699

**Comment by joehand** [comment]
> @joehand When I try npm package install on a clean project I still get a lot of warnings: https://gist.github.com/aschrijver/def029ad7ac6581d8e7530f27c877699

Those are native modules which pkg doesn't support.

**Comment by joehand** [comment]
This is working!
