### ISSUE TITLE
two way sharing, both server and client?

### ISSUE THREAD

**Issue by futurist** [datproject/dat#878]
How to sharing files two way? That is 2 peers both be server and be client.

Example:

ClientA put into share folder FileA, that file auto synced into ClientB's share folder.

Then ClientB put FileB into his/her share folder, that file also auto synced into ClientA's share folder.

Is is possible? How to setup using dat?

**Comment by joehand** [comment]
This is in development, and a high priority. But it is not possible right now. 

We refer to it as *multiwriter* around the documentation and here. Initial implementation is happening in [hyperdb](https://github.com/mafintosh/hyperdb/) which will be used under the hood for Dat.

**Comment by joehand** [comment]
See #827 for future discussion of two way sharing.
