### ISSUE TITLE
Please offer the 'dat' commandline tool for download as an AppImage

### ISSUE THREAD

**Issue by KurtPfeifle** [datproject/dat#897]
As you may be aware that BeakerBrowser is available as a binary [AppImage](https://appimage.org/) for download. 

AppImages are a special kind of packaging Linux applications into on single file, which can be directly *run across a big set of Linux distributions* (after making the file executable, of course).

What you *MAY* miss when quickly reading the website or the GitHub resources about AppImage: this format is not only for desktop applications -- it works equally well with command line tools.

If you offered *`dat`* as a pre-compiled AppImage, this would help it a lot to become known and more popular faster:
- Users would not have to compile it themselves. (Many aren't THAT technical, and they'll rather wait, until a new thing ships thru the package repositories of their $distro of choice.) And you could possibly convince packagers for many $distros to start packaging *`dat`*, when they can quickly play already with it in its AppImage incarnation, finding out it's cool enough to ship thru the official distro channels!
- You as developers would share the very same "user experience" as the users themselves. When debugging something or dealing with many of your [issues](https://github.com/datproject/dat/issues), you'd not first have to re-produce the bug on possibly the same system as your user. And you could easily point the user to a bugfixed version, which she/he could easily download and directly use, irrespective of distro version.

One other advantage of AppImage format is that you can easily run side by side different versions of the same application. Debugging the interaction between a *`dat v14`*  vs a `dat v15` can be done on the same system, using just two different terminal windows, instead of possibly to different containers or VMs.

If you have any questions about how to create AppImage packages for CLI applications: don't hesitate to drop by in the [IRC channel #AppImage on Freenode](https://webchat.freenode.net/?channels=appimage).

I'm pretty sure that @probonopd and others will enjoy to help you with initial problems. You could even have an automatic Travis CI build of an AppImage for your tool(s) upon each release (or, if you want, as a "continuous" release upon each Git commit/push you do).

**Comment by okdistribute** [comment]
We are offering it as an executable and as an AppImage with [github.com/datproject/dat-desktop](github.com/datproject/dat-desktop)
