### ISSUE TITLE
PhoneGap / Browser Implementation?

### ISSUE THREAD

**Issue by chadananda** [datproject/dat#904]
We have a educational hybrid app which manages lots of small audio files. We want to provide file sharing between students without hitting the (very expensive) internet. 

Even in our browser interface with Chrome we have about 15GB of local storage to work with for caching our audio files.

I don't see any reference to browser or hybrid app implementation here. Has anyone worked on something like this? It seems like an obvious use-case for rural classrooms.

**Comment by creationix** [comment]
I'd love this as well.  I'm currently working on some gateway/proxy/relay stuff where browsers talk to a localhost websocket server which then speaks the more interesting P2P protocols, but lets me keep all my crypto in the browser side.  The websocket server is pretty much a dumb transport that can't read the actual data.  It just knows enough to route the packets to where they need to go.

Something similar could be done for dat.  Also projects like hypercored expose the dat replication protocol over websocket directly.

I'm interested to see more work in this direction, especially for mobile.

**Comment by carloslfu** [comment]
Hi @chadananda geat project!, there is a cordova / phonegap plugin that lets you run node.js libraries, see [here](https://github.com/janeasystems/nodejs-mobile-cordova). You can use [dat-node](https://github.com/datproject/dat-node) and this cordova plugin for running Dat in an hybrd app. Hope it helps.

**Comment by okdistribute** [comment]
We recommend using [https://github.com/JaneaSystems/nodejs-mobile-react-native](https://github.com/JaneaSystems/nodejs-mobile-react-native), see https://github.com/digidem/mapeo-mobile for a reference implementaiton
