### ISSUE TITLE
dat.cli versioning

### ISSUE THREAD

**Issue by jakemontreal** [datproject/dat#906]
Hi dat team, I see in your documentation that "We are working on adding a local version history backup in the command line and desktop application. The interfaces for using and checking out older versions will also be further developed."

Is there any progress on the local version history backup from command line? There isn't really a good solution to navigating the version history atm. Thanks! Jake

**Comment by okdistribute** [comment]
You can hit `dat log` but there is no way to currently go back in time, this might be out of scope of the dat cli for the forseeable future. Check out https://cobox.cloud/
