### ISSUE TITLE
Hyperlinking (in Windows)

### ISSUE THREAD

**Issue by brandoncomputer** [datproject/dat#907]
There is never a good way to release a shim or front end. Only halfway good attempts.

Regard link. [dat.zip](https://github.com/datproject/dat/files/1581412/dat.zip)
`
#dat.ps1
#window flash unresolvable. See https://github.com/PowerShell/PowerShell/issues/3028
#Run this script once with no parameters to "installl" this protocol. This will allow the hyperlinking of dat:// within most web browsers in windows - with the most notable exception being Edge.

param([string]$uri)
$invocation = (Get-Variable MyInvocation).Value
$invocationpath = '"' + $invocation.MyCommand.Path + '"'

New-Item 'HKCU:\Software\Classes\Dat' -Force | New-ItemProperty -Name "(Default)" -Value "Dat Uri" -Force | New-ItemProperty -Name "URL Protocol" -Value "" -Force | New-ItemProperty -Name "Content Type" -Value "application/x-dat" -Force | Out-Null
New-Item 'HKCU:\Software\Classes\Dat\shell' -Force | New-ItemProperty -Name "(Default)" -Value "open" -Force | Out-Null
New-Item 'HKCU:\Software\Classes\Dat\shell\open\command' -Force | New-ItemProperty -Name "(Default)" -Value `""C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`"` -windowstyle Hidden -nologo -executionpolicy bypass -sta -file $invocationpath -uri `"`%1`"` " -Force | Out-Null

$directorypath = Split-Path $invocation.MyCommand.Path
$filepath = $directorypath + '\' + $uri.TrimStart("dat://")
       cd $directorypath

#twice on purpose. Once to clone, once to watch changes.
Start-Process -filePath dat -Argumentlist "clone $uri" -passthru -NoNewWindow
Start-Process -filePath dat -Argumentlist "clone $uri" -passthru -NoNewWindow

sleep 1
Invoke-Item $filepath
`

**Comment by okdistribute** [comment]
We need more information to debug this
