### ISSUE TITLE
Unable to connect p2p(Ubuntu Amazon EC2 Instance)

### ISSUE THREAD

**Issue by pavanguru423** [datproject/dat#912]
I have enabled ports 3282 and 8080 on my EC2 instance and below is the error I am getting while running dat doctor:

[info] Testing connection to public peer
[error] FAIL - Connection timeout, fail.
[error] FAIL - Connection timeout, fail.
[error] FAIL - Unable to connect to public server.
[error] FAIL - Data was not echoed back from public server.
dat: src/unix/udp.c:64: uv__udp_finish_close: Assertion `!uv__io_active(&handle->io_watcher, 1 | 4)' failed.
I have even tried to disable iptables and run the above command but still no luck. Can anyone please help me with this?

**Comment by joehand** [comment]
We have been having some discovery issues lately that we'll be looking into. 

Were you able to do any peer-to-peer connections via Dat doctor (run `dat doctor` EC2 then it'll print out a key and run `dat doctor <key>` on another computer).

The UDP error may point to other issues though...

**Comment by pavanguru423** [comment]
I have run the dat doctor command and below is the error I got:

[info] Testing connection to public peer
[error] FAIL - Connection timeout, fail.
[error] FAIL - Connection timeout, fail.
[error] FAIL - Unable to connect to public server.
[error] FAIL - Data was not echoed back from public server.
dat: src/unix/udp.c:64: uv__udp_finish_close: Assertion `!uv__io_active(&handle->io_watcher, 1 | 4)' failed.

**Comment by okdistribute** [comment]
This should be fixed on dat 14.0.2 on node 12, please re-open if you continue to see issues.
