### ISSUE TITLE
localhost discovery

### ISSUE THREAD

**Issue by dcposch** [datproject/dat#917]
right now dat supports DNS, DHS, and mDNS (LAN) discovery

however, when i run `dat share` and then try to visit the resulting dat in Beaker on the same computer, it doesn't load

does `dat` have a mechanism to talk to another instance of `dat` running on localhost?

@mafintosh

**Comment by pfrazee** [comment]
Huh, this usually works for me

**Comment by buckle2000** [comment]
Same here. I cannot `dat clone` from localhost.

**Comment by joehand** [comment]
> Same here. I cannot dat clone from localhost dat share.

@buckle2000 hmm, can you give us some more details on your setup? What OS are you on? What node version (`node -v`), dat version (`dat -v`)?

A few other things to help debug, if you have time:

* Run `dat doctor` in one window, it'll print out a key at the end. Run that in another window, `dat doctor <key>`. Does that connect?
* Run `DEBUG=dat* dat share` and `DEBUG=dat* dat clone` for a bit and then share the logs.

**Comment by buckle2000** [comment]
OS: Windows 10 (version 1511; 10586.104)
node version: 8.2.1
dat version: 13.10.0

`dat doctor` works fine.

[dat clone.log](https://github.com/datproject/dat/files/1705270/dat.clone.log)
[dat share.log](https://github.com/datproject/dat/files/1705271/dat.share.log)

For some reasons, `dat share` prints out incorrect file paths / append `C:` to any path. For instance `./.dat` -> `C:\\.dat`.

**Comment by joehand** [comment]
Awesome thanks! Looks like maybe they are getting connected (since doctor works and the streams try to start) but there is some other underlying issue.

> For some reasons, dat share prints out incorrect file paths / append C: to any path. For instance ./.dat -> C:\\.dat.

I was probably just lazy and didn't use `path.sep`.

**Comment by opensourcer2** [comment]
Has this been fixed yet? I am getting the same `C:` prepend to all paths and `dat share` does not work on Windows.

**Comment by okdistribute** [comment]
This bug could be related to this module https://github.com/random-access-storage/random-access-file

the cli has no lead on it currently, so PRs welcome if you can figure out the issue!

**Comment by opensourcer2** [comment]
@okdistribute Looks like there is already a PR here https://github.com/datproject/dat-node/pull/240

**Comment by RangerMauve** [comment]
@opensourcer2 That should have been [fixed in 2.1.2](https://github.com/random-access-storage/random-access-file/pull/20#issuecomment-493048837)

**Comment by okdistribute** [comment]
@RangerMauve I wonder if that made it to the dat executable though, we might need to rebuild it?

**Comment by okdistribute** [comment]
This should be fixed in 14.0.1, please let us know
