### ISSUE TITLE
Type script support

### ISSUE THREAD

**Issue by BioPhoton** [datproject/dat#920]
Hi awesome Dat Team!!!

Will there be TypeScript support somewhere in the future?

Best 
Michael

**Comment by joehand** [comment]
What is required to support TypeScript? Not quite sure what this means or would entail.

**Comment by BioPhoton** [comment]
Well, the things that would change are:
- all files needs to be ending with .ts
- the code could be typed
- you may use classes
- the tooling needs an additional step to compile from .ts to js. But that's trivial.

**Comment by joehand** [comment]
Oh I misunderstood, I you meant supporting in external TypeScript projects, not changing this project to TypeScript.

Changing everything to TypeScript isn't something we'd support. We try to avoid compilation and unnecessary overhead (mental shifts, onboarding, etc.) as much as possible.
