### ISSUE TITLE
TypeScript external projects support

### ISSUE THREAD

**Issue by carloslfu** [datproject/dat#921]
TypeScript external support as so many JS libraries does implies to include a `dat.d.ts` file in the published npm files. For example Electron project puts an [electron.d.ts](https://unpkg.com/electron@1.7.11/electron.d.ts) type definition file in the npm registry, and add a `types` field in the `package.json` with the file name. Other method is to publish to the DefinetlyTyped repo a `@types/dat` folder with the type definitions. As described [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by joehand** [comment]
It seems like this may be a better fit at a PR to the [dat-node repo](https://github.com/datproject/dat-node)? The Dat JS API is exported directly from there.

**Comment by carloslfu** [comment]
Yes it would be better

**Comment by carloslfu** [comment]
I can work on the PR

**Comment by okdistribute** [comment]
Thanks, can you open this on dat-node or even better, Hypercore or Hyperdrive?
