### ISSUE TITLE
dat package is including node v8.0.0

### ISSUE THREAD

**Issue by joehand** [datproject/dat#924]
When running on debug, it prints out node v8.0.0. Do we need to specify latest or something? Or we are printing out the wrong node version?

```
DEBUG=dat* /Users/joe/Downloads/dat-13.10.0-macos-x64/dat share .
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.10.0 +7ms
  dat node v8.0.0 +1ms
```

**Comment by millette** [comment]
Related: https://github.com/zeit/pkg/issues/330
