### ISSUE TITLE
trying to run dat behind a firewall

### ISSUE THREAD

**Issue by fernandezpablo85** [datproject/dat#926]
I'm trying to make clone a dat from a different machine in the same vpn, problem is, there's a firewall and few ports are exposed on the machine (9290 and 9292).

What I've tried so far is:

`dat share`

`dat share --port 9290`

And on the other machine:

`dat clone dat://hash`

`dat clone dat://hash --port 9290`

With no luck.

Also, dat doctor fails on both boxes (with and without --port 9290 option set)

**Comment by fernandezpablo85** [comment]
Hi guys, any updates on this one?

**Comment by pfrazee** [comment]
We've got plans to improve the discovery network soon; this may just be discovery failing. @joehand is it possible there are any bugs or issues with his husage?

**Comment by joehand** [comment]
Can you share the output of `dat doctor`? I'd also be helpful to run the share/clone commands with debug on:

```
DEBUG=dat* dat share
```

**Comment by okdistribute** [comment]
Can you see if this is fixed now on dat 14.0.2 (npm install -g dat@next, or latest binaries?)
