### ISSUE TITLE
dat publish triggering "TypeError: cb is not a function"

### ISSUE THREAD

**Issue by abevoelker** [datproject/dat#928]
I don't know if this issue belongs here or in [joehand/dat-json](https://github.com/joehand/dat-json).

> 1. Summary of the issue you are experiencing.

I created a site in the Beaker browser yesterday. Today I installed this `dat` tool, and decided to try publishing my site to the datbase.org registry. I browsed to my site's directory, executed `dat publish`, and got:

```
No existing dat in this directory. Create a dat before publishing.
```

So I went up a directory, did a `dat clone dat://blog.abevoelker.com`, and it output a fresh directory with my site in it. I cd'ed to that directory, and tried `dat publish` again, but got:

```
$ dat publish
Publishing dat to datbase.org!

dat name:  abes-blog
Please wait, 'abes-blog' will soon be ready for its great unveiling...
/home/abe/.config/yarn/global/node_modules/dat-json/index.js:20
      if (!archive.writable) return cb(new Error('Archive not writable'))
                                    ^

TypeError: cb is not a function
    at Object.write (/home/abe/.config/yarn/global/node_modules/dat-json/index.js:20:37)
    at /home/abe/.config/yarn/global/node_modules/dat/src/commands/publish.js:118:17
    at Request._callback (/home/abe/.config/yarn/global/node_modules/township-client/index.js:163:12)
    at Request.self.callback (/home/abe/.config/yarn/global/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/abe/.config/yarn/global/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/abe/.config/yarn/global/node_modules/request/request.js:1085:12)
```

If I put a `console.log(cb)` right above line 20 in that file, and it seems that `cb` is undefined:

```
$ dat publish
Publishing dat to datbase.org!

dat name:  abes-blog
Please wait, 'abes-blog' will soon be ready for its great unveiling...
undefined
/home/abe/.config/yarn/global/node_modules/dat-json/index.js:21
      if (!archive.writable) return cb(new Error('Archive not writable'))
...
```

Apparently the write function is being called with two arguments:

https://github.com/datproject/dat/blob/2d7c9602bc32edbcc2edbf48d4a772493f2687cd/src/commands/publish.js#L118

when it expects three (the third one being the callback):

https://github.com/joehand/dat-json/blob/1ae1fa068a20d4eccae6927a7b6c59adb44037ce/index.js#L19

> 2. Details on what versions of node and dat you have (node -v and dat -v).

```
$ node -v
v7.10.1
$ dat -v
13.10.0
```

**Comment by joehand** [comment]
Awesome issue documentation!

Ya, this is a bit tricky. Few things going on:

1. Beaker and Dat aren't storing the metadata files in the same way right now, meaning you can't use the CLI with Beaker-created stuff.
2. To publish, we require an archived to be owned by the user that is publishing (e.g. `archive.writeable`). Otherwise anyone could publish someone else's data.

To publish it, you could create it first with Dat and then clone it over to Beaker, but still not ideal.

Regardless, we should make this error more user-friendly.

**Comment by abevoelker** [comment]
Thanks for that explanation - I was thinking it was a file permission issue at first based on that message, and partly because I had some npm permission issues earlier in the day that I fixed. But I had double checked all of the site and node_modules permissions and everything looked fine.

Will try your suggestion later, thanks!
