### ISSUE TITLE
Exit from dat sync after syncing with one peer

### ISSUE THREAD

**Issue by mitar** [datproject/dat#936]
I am trying to sync many dat files to a hypercored instance. I listed hashes I care about in its feeds file, but now I have to run `dat sync` for as long that the dat file gets synced there. But the issue is that I would like to automatize this process. Ideally, it would sync only for one peer and after that peer would get the whole dat, it would exit. So that I can then do this for the next dat repo.

I tried both [dat-daemon](https://github.com/soyuka/dat-daemon) and [dat-share-all](https://www.npmjs.com/package/dat-share-all) but each had some issues, especially if there are 1000 dats to share. This is why I would just run them one by one.

**Comment by joehand** [comment]
Yea, great feature request. 

We have this in https://github.com/datproject/dat/issues/648 too, so I'll close this as a duplicate for now. Thanks for reminding me though.

**Comment by mitar** [comment]
My current workaround:

```python
#!/usr/bin/env python

# Shares dat one after the other. (After you press ctrl-c to cancel the current one.)

import os
import signal
import subprocess
import sys

for dirpath, dirnames, filenames in os.walk('.', followlinks=True):
    if 'dat.json' not in filenames:
        continue

    directory_path = os.path.abspath(dirpath)

    print("Sharing '{directory_path}'.".format(directory_path=directory_path))

    process = subprocess.Popen(['dat', 'sync', '--no-watch'], cwd=directory_path, stdout=subprocess.PIPE, stderr=sys.stderr, encoding='utf8')

    state = 0

    while True:
        line = process.stdout.readline()
        if line == '' and process.poll() is not None:
            break
        sys.stdout.write(line)
        sys.stdout.flush()

        if state == 0 and 'Exiting the Dat program...' in line:
            state = 1

        if state == 1 and '0 B/s' in line:
            process.send_signal(signal.SIGINT)

    if process.returncode != 0:
        raise Exception("Non-zero return code.")
```
