### ISSUE TITLE
When running multiple "dat share" only the first port is accessible from outside

### ISSUE THREAD

**Issue by mitar** [datproject/dat#947]
Slight followup to #945. I noticed that if I run `dat share` multiple times on my machine, only the first instance (the one using the default port) can be accessible from outside, but others are not (connection time outs).

I have INPUT policy ACCEPT on a machine testing it, but the machine is behind a NAT. I looked at upnp mappings on my router and it was empty. It is a cheap router, so maybe something is not being displayed, because I would expect that at least the first instance is seen there?

My guess is that maybe upnp uses the same service name for all instances so it confuses something and only the first port gets mapped?

**Comment by mitar** [comment]
That's then probably a reason why I could not find anything in the upnp list on the router. :-)

But data transmissions go over TCP, no? How are they opened?

**Comment by pfrazee** [comment]
Dat uses both TCP and UTP (which is built on UDP). TCP only gets used (afaik) within a LAN and when transacting with public peers like Hashbase. UTP gets used on everything.

**Comment by vqthanh** [comment]
![er](https://user-images.githubusercontent.com/36762946/37208823-572266ba-23d5-11e8-90aa-db6b4291beff.png)
I'm not sure how to describe this problem, I'm just a normal user

**Comment by okdistribute** [comment]
14.0.2 now accepts hole punching, so hopefully your computers will be discoverable now without explicit port forwarding. Please try it and let us know!
