### ISSUE TITLE
Can't create new Dat in subfolder of existing Dat

### ISSUE THREAD

**Issue by chartgerink** [datproject/dat#971]
`dat create <dir>` works when I create a new Dat in any non-Dat folder, but not when I create it from *within* a Dat folder. It then states `dat already exists`. 

It seems like this check makes perfect sense, but it should function on the dir specified, right? [I was checking out the code](https://github.com/datproject/dat/blob/master/src/commands/create.js#L57) but couldn't quite figure out what to change to rectify this. Would be happy to submit a PR if anybody can indicate what needs to be adjusted.

**Comment by chartgerink** [comment]
Oh wait sorry, <dir> functionality isn't part of dat create it seems?

**Comment by joehand** [comment]
hmm the `dir` option should work with create https://github.com/datproject/dat/blob/master/src/commands/create.js#L32

Can you run it with `DEBUG=dat*` just to see if something weird is happening?

**Comment by chartgerink** [comment]
Wow that's super odd, with `DEBUG=dat*` it does work?

```bash
[chjh@spectacle playground]$ ls -la
total 48
drwxrwxr-x. 10 chjh chjh 4096 Apr  5 14:32 .
drwx------. 55 chjh chjh 4096 Apr  5 21:24 ..
drwxrwxr-x.  4 chjh chjh 4096 Mar  7 16:39 43dfc9f23fdded8cc7c01c71c0702a0529130af0258e7fb30bf5a0a3f73d69b3
drwxrwxr-x.  4 chjh chjh 4096 Mar  7 11:58 archiver
drwxrwxr-x.  2 chjh chjh 4096 Apr  5 12:35 .dat
-rw-rw-r--.  1 chjh chjh 1517 Mar  7 11:58 deposit.json
-rw-rw-r--.  1 chjh chjh   61 Mar  7 11:58 feeds
drwxrwxr-x.  5 chjh chjh 4096 Mar 13 15:00 node-js-getting-started
drwxrwxr-x.  3 chjh chjh 4096 Mar  8 14:30 proj.mgmt
drwxrwxr-x.  9 chjh chjh 4096 Mar 23 16:04 puniform
drwxrwxr-x.  3 chjh chjh 4096 Apr  5 14:30 test
drwxrwxr-x.  3 chjh chjh 4096 Apr  5 14:32 test2
[chjh@spectacle playground]$ dat create testtttt DEBUG=dat*
Welcome to dat program!
You can turn any folder on your computer into a Dat.
A Dat is a folder with some magic.

Your dat is ready!
We will walk you through creating a 'dat.json' file.
(You can skip dat.json and get started now.)

Learn more about dat.json: https://github.com/datprotocol/dat.json

Ctrl+C to exit at any time

Title:  

Created empty Dat in /home/chjh/playground/DEBUG=dat*/.dat

Now you can add files and share:
* Run dat share to create metadata and sync.
* Copy the unique dat link and securely share it.

dat://401e7360c18d08f1b7fe7711d719c62c9f3cdfee551ccc25642394c2e01ae839
[chjh@spectacle playground]$ dat create test123
Welcome to dat program!

Archive already exists.
You can use `dat sync` to update.
[chjh@spectacle playground]$ 
```

**Comment by joehand** [comment]
Oh sorry, it should go before the command =) ` DEBUG=dat* dat create testtttt`

Does look like there is some arg parsing error though, since its using the 4th arg for the directory.

**Comment by chartgerink** [comment]
;-) No rush on my end. Let me know if you need me to run anything :)

**Comment by okdistribute** [comment]
Try [https://github.com/andrewosh/hyperdrive-daemon](https://github.com/andrewosh/hyperdrive-daemon) or [https://cobox.cloud/](https://cobox.cloud/), which will support this.
