### ISSUE TITLE
Indexing a dat containing a named pipe freezes

### ISSUE THREAD

**Issue by Tangent128** [datproject/dat#979]
I am reporting:

- [X] a bug or unexpected behavior
- [ ] feature request
- [ ] security issue 
- [ ] general feedback

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: Archlinux 32-bit
* Node Version: v9.11.1
* Dat Version: 13.10.0

### Expected behavior

When creating a dat from a directory tree containing a named pipe, I expect the operation to complete, rather than hanging indefinitely when it encounters the named pipe.

I personally would be fine if the archive simply skipped the named pipe; if the archive format is capable of describing pipes, though, then including the pipe would probably be "correct".

### Actual behavior

Dat reaches the named pipe in its import, reports it as 0b in size, yet never moves on. Presumably, it is trying to open it and read its contents.

**Comment by joehand** [comment]
We added this to mirror-folder, need to update to fix: https://github.com/mafintosh/mirror-folder/pull/15
