### ISSUE TITLE
dat keys is not included in dat help output

### ISSUE THREAD

**Issue by tmcw** [datproject/dat#981]
I am reporting:

- [ ] a bug or unexpected behavior
- [x] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: macos 10.13.4
* Node Version: 8.9.4
* Dat Version: 13.10.0

### Expected behavior

I expect the `dat help` command to list all available commands

### Actual behavior

The `dat keys` command is not included in the list of usable dat commands, making it difficult to discover from the perspective of the dat CLI tool.

**Comment by brechtcs** [comment]
I can't immediately find the issue, but I remember reading somewhere that this was done on purpose. The reason is that `dat keys` is only a temporary solution that's not advisable to inexperienced users. It's supposed to be replaced by full support for multiple writers when it lands.

**Comment by joehand** [comment]
Thanks for opening @tmcw! @brechtcs got it correct in the reasoning. We could add that note to the help though, since this command is still useful to know about!

**Comment by millette** [comment]
[The comment in 983](https://github.com/datproject/dat/issues/983#issuecomment-384661775) mentions they ```keys``` command.

**Comment by okdistribute** [comment]
Fixed on master, thanks!
