### ISSUE TITLE
Running a gateway?

### ISSUE THREAD

**Issue by leethax666** [datproject/dat#988]
I don't see any docs on running a gateway for the Firefox extension, nor any command line options in dat. Is there currently a way to do this?

**Comment by joehand** [comment]
There is a built in http server if you run with `--http` but not sure of the compatibility with dat firefox extension. There is a gateway listed in the instructions of dat-fox: https://github.com/sammacbeth/dat-fox. Hopefully that one works!

**Comment by sull** [comment]
How do you kill the http server after running --http flag?
