### ISSUE TITLE
outdated versions of dat should give nice error messages

### ISSUE THREAD

**Issue by karissa** [datproject/dat#992]
It'd be cool if outdated dats could be detected and give a nice message to say 'Hey, update your dat' with a link to instructions on how to do that. And then if you want the stack trace you can add `--verbose` or `--debug` or something.

```js
Connecting to dat network...
/Users/karissa/node_modules/dat/node_modules/append-tree/index.js:636
      if (offset >= buf.length) throw new Error('Invalid index')
                                ^

Error: Invalid index
    at Tree._inflate (/Users/karissa/node_modules/dat/node_modules/append-tree/index.js:636:39)
    at Tree._list (/Users/karissa/node_modules/dat/node_modules/append-tree/index.js:132:24)
    at /Users/karissa/node_modules/dat/node_modules/append-tree/index.js:112:10
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by joehand** [comment]
What version was the dat created with? I thought we had a nice message for the last breaking change, but haven't seen it for awhile so maybe could have regressed.

**Comment by karissa** [comment]
@joehand I realized that this is actually a hyperdb dat..

**Comment by joehand** [comment]
> @joehand I realized that this is actually a hyperdb dat..

ah cool! We will definitely have nice messages for that down the road. In the meantime we can use https://github.com/joehand/dat-next
